import os
import json
import time
import html
import random
import asyncio
import threading
import requests
from http.server import HTTPServer, BaseHTTPRequestHandler
from telegram import Bot

# ==========================================
# 1. HEALTH CHECK SERVER
# ==========================================
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Bot status: OK & Running")
    def log_message(self, format, *args):
        pass

def run_server():
    port = int(os.environ.get("PORT", 8080))
    HTTPServer(('0.0.0.0', port), HealthHandler).serve_forever()

threading.Thread(target=run_server, daemon=True).start()

# ==========================================
# 2. CONFIG
# ==========================================
TOKEN         = os.environ["BOT_TOKEN"]
CHAT_ID       = os.environ["CHAT_ID"]
RENDER_URL    = os.environ.get("RENDER_URL", "")
GIST_ID       = os.environ["GIST_ID"]
GITHUB_TOKEN  = os.environ["GITHUB_TOKEN"]

GIST_API = f"https://api.github.com/gists/{GIST_ID}"
GH_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

# ==========================================
# 3. GIST PERSISTENCE
# ==========================================
def load_sent_words():
    try:
        r = requests.get(GIST_API, headers=GH_HEADERS, timeout=10)
        content = r.json()["files"]["sent.json"]["content"]
        data = json.loads(content)
        print(f"[GIST] Loaded {len(data)} sent words")
        return set(w.lower() for w in data)
    except Exception as e:
        print(f"[GIST] Load failed: {e}")
        return set()

def save_sent_words(sent_set):
    for attempt in range(3):
        try:
            r = requests.patch(
                GIST_API,
                headers=GH_HEADERS,
                json={"files": {"sent.json": {
                    "content": json.dumps(sorted(sent_set), ensure_ascii=False)
                }}},
                timeout=10
            )
            if r.status_code == 200:
                print(f"[GIST] Saved {len(sent_set)} words")
                return True
        except Exception as e:
            print(f"[GIST] Save error: {e}")
        time.sleep(2)
    return False

SENT_WORDS = load_sent_words()

# ==========================================
# 4. FRENCH VOCABULARY — 1200 WORDS WITH SENTENCES
# Format: (word, meaning, example sentence)
# ==========================================
VOCAB_DATABASE = [
    # ===== GREETINGS & POLITENESS (1-40) =====
    {"word": "Bonjour", "meaning": "Hello / Good morning", "example": "Bonjour, comment allez-vous ?"},
    {"word": "Bonsoir", "meaning": "Good evening", "example": "Bonsoir, on dîne bientôt."},
    {"word": "Salut", "meaning": "Hi / Bye (informal)", "example": "Salut, ça va bien ?"},
    {"word": "Bonne nuit", "meaning": "Good night", "example": "Bonne nuit, fais de beaux rêves."},
    {"word": "Au revoir", "meaning": "Goodbye", "example": "Au revoir, à demain !"},
    {"word": "À bientôt", "meaning": "See you soon", "example": "À bientôt, mon ami."},
    {"word": "À demain", "meaning": "See you tomorrow", "example": "À demain à l'école."},
    {"word": "Merci", "meaning": "Thank you", "example": "Merci pour ton aide."},
    {"word": "Merci beaucoup", "meaning": "Thank you very much", "example": "Merci beaucoup pour ce cadeau."},
    {"word": "De rien", "meaning": "You're welcome", "example": "De rien, c'était un plaisir."},
    {"word": "S'il vous plaît", "meaning": "Please (formal)", "example": "Un café, s'il vous plaît."},
    {"word": "Pardon", "meaning": "Sorry / Excuse me", "example": "Pardon, je suis en retard."},
    {"word": "Excusez-moi", "meaning": "Excuse me", "example": "Excusez-moi, où est la gare ?"},
    {"word": "Désolé", "meaning": "Sorry", "example": "Je suis désolé pour hier."},
    {"word": "Oui", "meaning": "Yes", "example": "Oui, je suis d'accord."},
    {"word": "Non", "meaning": "No", "example": "Non, je ne peux pas venir."},
    {"word": "Peut-être", "meaning": "Maybe", "example": "Peut-être qu'il viendra demain."},
    {"word": "Bien sûr", "meaning": "Of course", "example": "Bien sûr, je t'aide."},
    {"word": "D'accord", "meaning": "Okay", "example": "D'accord, on se voit à midi."},
    {"word": "Enchanté", "meaning": "Nice to meet you", "example": "Enchanté de faire votre connaissance."},
    {"word": "Bienvenue", "meaning": "Welcome", "example": "Bienvenue chez nous !"},
    {"word": "Félicitations", "meaning": "Congratulations", "example": "Félicitations pour ton diplôme !"},
    {"word": "Bonne chance", "meaning": "Good luck", "example": "Bonne chance pour ton examen."},
    {"word": "Bon voyage", "meaning": "Have a good trip", "example": "Bon voyage en France !"},
    {"word": "Bon appétit", "meaning": "Enjoy your meal", "example": "Bon appétit à tous !"},
    {"word": "Santé", "meaning": "Cheers / Health", "example": "Santé ! À ta réussite."},
    {"word": "Joyeux anniversaire", "meaning": "Happy birthday", "example": "Joyeux anniversaire, ma chérie !"},
    {"word": "Bonne année", "meaning": "Happy new year", "example": "Bonne année et bonne santé !"},
    {"word": "Joyeux Noël", "meaning": "Merry Christmas", "example": "Joyeux Noël à toute la famille !"},
    {"word": "Bonne journée", "meaning": "Have a good day", "example": "Bonne journée au travail !"},
    {"word": "Comment allez-vous", "meaning": "How are you (formal)", "example": "Comment allez-vous aujourd'hui ?"},
    {"word": "Ça va", "meaning": "I'm fine", "example": "Ça va bien, merci."},
    {"word": "Pas mal", "meaning": "Not bad", "example": "Pas mal, et toi ?"},
    {"word": "Très bien", "meaning": "Very well", "example": "Très bien, je te remercie."},
    {"word": "Comme ci comme ça", "meaning": "So-so", "example": "Comme ci comme ça, ça peut aller."},
    {"word": "De rien du tout", "meaning": "It's nothing", "example": "De rien du tout, c'est normal."},
    {"word": "Excusez-moi de vous déranger", "meaning": "Sorry to bother you", "example": "Excusez-moi de vous déranger, mais j'ai une question."},
    {"word": "Je vous en prie", "meaning": "You're welcome (formal)", "example": "Je vous en prie, c'est un plaisir."},
    {"word": "Avec plaisir", "meaning": "With pleasure", "example": "Avec plaisir, je viendrai."},
    {"word": "Amitiés", "meaning": "Best wishes / Regards", "example": "Amitiés à toute ta famille."},

    # ===== ESSENTIAL VERBS (41-190) =====
    {"word": "Être", "meaning": "To be", "example": "Je suis étudiant."},
    {"word": "Avoir", "meaning": "To have", "example": "J'ai deux frères."},
    {"word": "Faire", "meaning": "To do / make", "example": "Je fais mes devoirs."},
    {"word": "Aller", "meaning": "To go", "example": "Je vais à Paris demain."},
    {"word": "Venir", "meaning": "To come", "example": "Elle vient de Lyon."},
    {"word": "Pouvoir", "meaning": "To be able to / can", "example": "Je peux t'aider."},
    {"word": "Vouloir", "meaning": "To want", "example": "Je veux un café."},
    {"word": "Devoir", "meaning": "To must / have to", "example": "Je dois partir maintenant."},
    {"word": "Savoir", "meaning": "To know (fact)", "example": "Je sais nager."},
    {"word": "Connaître", "meaning": "To know (person)", "example": "Je connais bien Marie."},
    {"word": "Voir", "meaning": "To see", "example": "Je vois la tour Eiffel."},
    {"word": "Regarder", "meaning": "To watch / look at", "example": "Nous regardons un film."},
    {"word": "Entendre", "meaning": "To hear", "example": "J'entends de la musique."},
    {"word": "Écouter", "meaning": "To listen", "example": "J'écoute la radio le matin."},
    {"word": "Parler", "meaning": "To speak / talk", "example": "Elle parle trois langues."},
    {"word": "Dire", "meaning": "To say", "example": "Qu'est-ce que tu dis ?"},
    {"word": "Demander", "meaning": "To ask", "example": "Je demande l'heure."},
    {"word": "Répondre", "meaning": "To answer", "example": "Il répond toujours vite."},
    {"word": "Penser", "meaning": "To think", "example": "Je pense que tu as raison."},
    {"word": "Croire", "meaning": "To believe", "example": "Je crois en toi."},
    {"word": "Trouver", "meaning": "To find", "example": "J'ai trouvé mes clés."},
    {"word": "Chercher", "meaning": "To look for", "example": "Je cherche mon portable."},
    {"word": "Donner", "meaning": "To give", "example": "Il me donne un livre."},
    {"word": "Prendre", "meaning": "To take", "example": "Je prends le train à huit heures."},
    {"word": "Mettre", "meaning": "To put", "example": "Mets ton manteau, il fait froid."},
    {"word": "Laisser", "meaning": "To leave / let", "example": "Laisse-moi tranquille !"},
    {"word": "Garder", "meaning": "To keep", "example": "Je garde ce souvenir."},
    {"word": "Acheter", "meaning": "To buy", "example": "J'achète du pain."},
    {"word": "Vendre", "meaning": "To sell", "example": "Il vend sa voiture."},
    {"word": "Payer", "meaning": "To pay", "example": "Je vais payer l'addition."},
    {"word": "Travailler", "meaning": "To work", "example": "Elle travaille à l'hôpital."},
    {"word": "Jouer", "meaning": "To play", "example": "Les enfants jouent au parc."},
    {"word": "Étudier", "meaning": "To study", "example": "J'étudie le français."},
    {"word": "Apprendre", "meaning": "To learn", "example": "J'apprends une nouvelle langue."},
    {"word": "Comprendre", "meaning": "To understand", "example": "Je ne comprends pas cette phrase."},
    {"word": "Expliquer", "meaning": "To explain", "example": "Peux-tu expliquer la règle ?"},
    {"word": "Oublier", "meaning": "To forget", "example": "J'ai oublié mes clés."},
    {"word": "Se souvenir", "meaning": "To remember", "example": "Je me souviens de ce jour."},
    {"word": "Aimer", "meaning": "To love / like", "example": "J'aime le chocolat."},
    {"word": "Adorer", "meaning": "To adore", "example": "J'adore cette chanson."},
    {"word": "Détester", "meaning": "To hate", "example": "Je déteste attendre."},
    {"word": "Préférer", "meaning": "To prefer", "example": "Je préfère le thé au café."},
    {"word": "Espérer", "meaning": "To hope", "example": "J'espère te voir bientôt."},
    {"word": "Attendre", "meaning": "To wait", "example": "J'attends le bus."},
    {"word": "Arriver", "meaning": "To arrive", "example": "Le train arrive à midi."},
    {"word": "Partir", "meaning": "To leave", "example": "Je pars en vacances demain."},
    {"word": "Rentrer", "meaning": "To return home", "example": "Je rentre à la maison."},
    {"word": "Rester", "meaning": "To stay", "example": "Je reste ici ce soir."},
    {"word": "Dormir", "meaning": "To sleep", "example": "Je dors huit heures par nuit."},
    {"word": "Se réveiller", "meaning": "To wake up", "example": "Je me réveille à sept heures."},
    {"word": "Se lever", "meaning": "To get up", "example": "Elle se lève tôt le matin."},
    {"word": "Se coucher", "meaning": "To go to bed", "example": "Je me couche à onze heures."},
    {"word": "Manger", "meaning": "To eat", "example": "Nous mangeons à midi."},
    {"word": "Boire", "meaning": "To drink", "example": "Je bois du café le matin."},
    {"word": "Cuisiner", "meaning": "To cook", "example": "Ma mère cuisine très bien."},
    {"word": "Marcher", "meaning": "To walk", "example": "Je marche dans le parc."},
    {"word": "Courir", "meaning": "To run", "example": "Il court vite."},
    {"word": "Nager", "meaning": "To swim", "example": "Elle nage à la piscine."},
    {"word": "Danser", "meaning": "To dance", "example": "Nous dansons toute la nuit."},
    {"word": "Chanter", "meaning": "To sing", "example": "Elle chante une belle chanson."},
    {"word": "Rire", "meaning": "To laugh", "example": "Nous rions ensemble."},
    {"word": "Pleurer", "meaning": "To cry", "example": "Ne pleure pas, tout va bien."},
    {"word": "Sourire", "meaning": "To smile", "example": "Elle sourit toujours."},
    {"word": "Lire", "meaning": "To read", "example": "Je lis un bon livre."},
    {"word": "Écrire", "meaning": "To write", "example": "J'écris une lettre à ma mère."},
    {"word": "Dessiner", "meaning": "To draw", "example": "L'enfant dessine un chat."},
    {"word": "Ouvrir", "meaning": "To open", "example": "Ouvre la fenêtre, s'il te plaît."},
    {"word": "Fermer", "meaning": "To close", "example": "Ferme la porte."},
    {"word": "Commencer", "meaning": "To start", "example": "Le film commence à huit heures."},
    {"word": "Finir", "meaning": "To finish", "example": "Je finis mon travail à six heures."},
    {"word": "Continuer", "meaning": "To continue", "example": "Continue comme ça !"},
    {"word": "Arrêter", "meaning": "To stop", "example": "Arrête de parler !"},
    {"word": "Changer", "meaning": "To change", "example": "Je change de chemise."},
    {"word": "Aider", "meaning": "To help", "example": "Peux-tu m'aider ?"},
    {"word": "Essayer", "meaning": "To try", "example": "J'essaie d'apprendre vite."},
    {"word": "Réussir", "meaning": "To succeed", "example": "Elle réussit à son examen."},
    {"word": "Échouer", "meaning": "To fail", "example": "Ne crains pas d'échouer."},
    {"word": "Gagner", "meaning": "To win / earn", "example": "Notre équipe a gagné."},
    {"word": "Perdre", "meaning": "To lose", "example": "J'ai perdu mon portefeuille."},
    {"word": "Envoyer", "meaning": "To send", "example": "Je t'envoie un message."},
    {"word": "Recevoir", "meaning": "To receive", "example": "J'ai reçu ton cadeau."},
    {"word": "Porter", "meaning": "To carry / wear", "example": "Elle porte une robe rouge."},
    {"word": "Montrer", "meaning": "To show", "example": "Montre-moi ton dessin."},
    {"word": "Cacher", "meaning": "To hide", "example": "Il cache un secret."},
    {"word": "Construire", "meaning": "To build", "example": "Ils construisent une maison."},
    {"word": "Réparer", "meaning": "To repair", "example": "Il répare ma voiture."},
    {"word": "Nettoyer", "meaning": "To clean", "example": "Je nettoie la cuisine."},
    {"word": "Laver", "meaning": "To wash", "example": "Je lave mes mains."},
    {"word": "Conduire", "meaning": "To drive", "example": "Elle conduit prudemment."},
    {"word": "Voyager", "meaning": "To travel", "example": "J'aime voyager en Europe."},
    {"word": "Visiter", "meaning": "To visit", "example": "Nous visitons le musée."},
    {"word": "Tomber", "meaning": "To fall", "example": "Attention, tu vas tomber !"},
    {"word": "Monter", "meaning": "To go up", "example": "Il monte les escaliers."},
    {"word": "Descendre", "meaning": "To go down", "example": "Descends du train ici."},
    {"word": "Tourner", "meaning": "To turn", "example": "Tourne à droite."},
    {"word": "Traverser", "meaning": "To cross", "example": "Traverse la rue prudemment."},
    {"word": "Suivre", "meaning": "To follow", "example": "Suivez-moi, s'il vous plaît."},
    {"word": "Pousser", "meaning": "To push", "example": "Pousse la porte."},
    {"word": "Tirer", "meaning": "To pull", "example": "Tire la corde."},
    {"word": "Lancer", "meaning": "To throw", "example": "Lance la balle !"},
    {"word": "Attraper", "meaning": "To catch", "example": "Attrape le ballon !"},
    {"word": "Toucher", "meaning": "To touch", "example": "Ne touche pas à ça."},
    {"word": "Sentir", "meaning": "To feel / smell", "example": "Je sens le parfum des fleurs."},
    {"word": "Appeler", "meaning": "To call", "example": "Je vais t'appeler ce soir."},
    {"word": "Raconter", "meaning": "To tell (story)", "example": "Raconte-moi ton voyage."},
    {"word": "Décrire", "meaning": "To describe", "example": "Décris-moi ta maison."},
    {"word": "Traduire", "meaning": "To translate", "example": "Peux-tu traduire cette phrase ?"},
    {"word": "Compter", "meaning": "To count", "example": "Compte jusqu'à dix."},
    {"word": "Mesurer", "meaning": "To measure", "example": "Il mesure un mètre quatre-vingts."},
    {"word": "Peser", "meaning": "To weigh", "example": "Combien pèses-tu ?"},
    {"word": "Choisir", "meaning": "To choose", "example": "Choisis ton plat."},
    {"word": "Décider", "meaning": "To decide", "example": "J'ai décidé de partir."},
    {"word": "Accepter", "meaning": "To accept", "example": "J'accepte ton invitation."},
    {"word": "Refuser", "meaning": "To refuse", "example": "Il refuse de venir."},
    {"word": "Permettre", "meaning": "To allow", "example": "Permettez-moi de parler."},
    {"word": "Interdire", "meaning": "To forbid", "example": "Il est interdit de fumer."},
    {"word": "Promettre", "meaning": "To promise", "example": "Je te promets de venir."},
    {"word": "Mentir", "meaning": "To lie", "example": "Ne me mens pas."},
    {"word": "Sauver", "meaning": "To save", "example": "Il a sauvé un enfant."},
    {"word": "Protéger", "meaning": "To protect", "example": "Protège-toi du froid."},
    {"word": "Blesser", "meaning": "To hurt", "example": "Il s'est blessé au pied."},
    {"word": "Soigner", "meaning": "To treat / care", "example": "Le médecin soigne le patient."},
    {"word": "Guérir", "meaning": "To heal", "example": "Il guérit lentement."},
    {"word": "Souffrir", "meaning": "To suffer", "example": "Elle souffre de la tête."},
    {"word": "Mourir", "meaning": "To die", "example": "Tout le monde doit mourir un jour."},
    {"word": "Vivre", "meaning": "To live", "example": "Je vis à Paris."},
    {"word": "Naître", "meaning": "To be born", "example": "Je suis né en 1990."},
    {"word": "Grandir", "meaning": "To grow", "example": "Les enfants grandissent vite."},
    {"word": "Créer", "meaning": "To create", "example": "Elle crée une entreprise."},
    {"word": "Détruire", "meaning": "To destroy", "example": "La guerre détruit tout."},
    {"word": "Inventer", "meaning": "To invent", "example": "Il a inventé une machine."},
    {"word": "Découvrir", "meaning": "To discover", "example": "J'ai découvert un bon restaurant."},
    {"word": "Ranger", "meaning": "To tidy", "example": "Range ta chambre !"},
    {"word": "Organiser", "meaning": "To organize", "example": "Elle organise une fête."},
    {"word": "Préparer", "meaning": "To prepare", "example": "Je prépare le dîner."},
    {"word": "Réaliser", "meaning": "To achieve", "example": "Il a réalisé son rêve."},
    {"word": "Terminer", "meaning": "To complete", "example": "Je termine mes devoirs."},
    {"word": "Reprendre", "meaning": "To resume", "example": "Reprenons la discussion."},
    {"word": "Abandonner", "meaning": "To abandon", "example": "N'abandonne jamais tes rêves."},
    {"word": "Hésiter", "meaning": "To hesitate", "example": "N'hésite pas à me demander."},
    {"word": "Oser", "meaning": "To dare", "example": "Ose dire ce que tu penses."},
    {"word": "Corriger", "meaning": "To correct", "example": "Le professeur corrige les copies."},
    {"word": "Vérifier", "meaning": "To verify", "example": "Vérifie ta réponse."},
    {"word": "Signer", "meaning": "To sign", "example": "Signez ici, s'il vous plaît."},
    {"word": "Effacer", "meaning": "To erase", "example": "Efface le tableau."},
    {"word": "Couper", "meaning": "To cut", "example": "Coupe le pain."},
    {"word": "Plier", "meaning": "To fold", "example": "Plie la serviette."},
    {"word": "Ouvrir un compte", "meaning": "To open an account", "example": "Je veux ouvrir un compte bancaire."},
    {"word": "Emprunter", "meaning": "To borrow", "example": "Puis-je emprunter ton stylo ?"},
    {"word": "Prêter", "meaning": "To lend", "example": "Il me prête son vélo."},
    {"word": "Rendre", "meaning": "To give back", "example": "Rends-moi mon livre."},
    {"word": "Garder le silence", "meaning": "To keep silent", "example": "Il garde le silence."},
    {"word": "Se reposer", "meaning": "To rest", "example": "Repose-toi bien ce week-end."},
    {"word": "S'amuser", "meaning": "To have fun", "example": "Les enfants s'amusent au parc."},
    {"word": "S'habiller", "meaning": "To get dressed", "example": "Habille-toi vite, on part."},
    {"word": "Se laver", "meaning": "To wash oneself", "example": "Je me lave les mains."},
    {"word": "Se promener", "meaning": "To take a walk", "example": "Nous nous promenons au bord de la mer."},

    # ===== FAMILY & PEOPLE (191-260) =====
    {"word": "Famille", "meaning": "Family", "example": "Ma famille est grande."},
    {"word": "Père", "meaning": "Father", "example": "Mon père travaille à la banque."},
    {"word": "Mère", "meaning": "Mother", "example": "Ma mère est très gentille."},
    {"word": "Papa", "meaning": "Dad", "example": "Papa, tu peux m'aider ?"},
    {"word": "Maman", "meaning": "Mom", "example": "Maman fait un gâteau."},
    {"word": "Parents", "meaning": "Parents", "example": "Mes parents habitent à Lyon."},
    {"word": "Frère", "meaning": "Brother", "example": "Mon frère est plus jeune que moi."},
    {"word": "Sœur", "meaning": "Sister", "example": "Ma sœur étudie la médecine."},
    {"word": "Grand-père", "meaning": "Grandfather", "example": "Mon grand-père a quatre-vingts ans."},
    {"word": "Grand-mère", "meaning": "Grandmother", "example": "Ma grand-mère fait très bien la cuisine."},
    {"word": "Oncle", "meaning": "Uncle", "example": "Mon oncle vit en Espagne."},
    {"word": "Tante", "meaning": "Aunt", "example": "Ma tante vient demain."},
    {"word": "Cousin", "meaning": "Cousin (m)", "example": "Mon cousin est médecin."},
    {"word": "Cousine", "meaning": "Cousin (f)", "example": "Ma cousine s'appelle Julie."},
    {"word": "Neveu", "meaning": "Nephew", "example": "Mon neveu a cinq ans."},
    {"word": "Nièce", "meaning": "Niece", "example": "Ma nièce adore les fleurs."},
    {"word": "Fils", "meaning": "Son", "example": "Leur fils est à l'université."},
    {"word": "Fille", "meaning": "Daughter / Girl", "example": "Sa fille est très intelligente."},
    {"word": "Enfant", "meaning": "Child", "example": "Cet enfant joue au parc."},
    {"word": "Bébé", "meaning": "Baby", "example": "Le bébé dort bien."},
    {"word": "Mari", "meaning": "Husband", "example": "Son mari est professeur."},
    {"word": "Femme", "meaning": "Wife / Woman", "example": "Sa femme est très belle."},
    {"word": "Ami", "meaning": "Friend (m)", "example": "Mon ami s'appelle Paul."},
    {"word": "Amie", "meaning": "Friend (f)", "example": "Mon amie habite à Paris."},
    {"word": "Voisin", "meaning": "Neighbor", "example": "Mon voisin est très sympa."},
    {"word": "Collègue", "meaning": "Colleague", "example": "Mes collègues sont sympas."},
    {"word": "Homme", "meaning": "Man", "example": "Cet homme est grand."},
    {"word": "Garçon", "meaning": "Boy", "example": "Le garçon joue au ballon."},
    {"word": "Monsieur", "meaning": "Sir / Mr.", "example": "Bonjour, Monsieur."},
    {"word": "Madame", "meaning": "Madam / Mrs.", "example": "Madame Dupont est absente."},
    {"word": "Mademoiselle", "meaning": "Miss", "example": "Mademoiselle, votre sac."},
    {"word": "Gens", "meaning": "People", "example": "Il y a beaucoup de gens ici."},
    {"word": "Personne", "meaning": "Person / Nobody", "example": "Cette personne est gentille."},
    {"word": "Docteur", "meaning": "Doctor", "example": "Le docteur est occupé."},
    {"word": "Médecin", "meaning": "Physician", "example": "Je vais chez le médecin."},
    {"word": "Professeur", "meaning": "Teacher / Professor", "example": "Le professeur explique la leçon."},
    {"word": "Étudiant", "meaning": "Student (m)", "example": "Cet étudiant est sérieux."},
    {"word": "Étudiante", "meaning": "Student (f)", "example": "Elle est étudiante en droit."},
    {"word": "Avocat", "meaning": "Lawyer", "example": "Mon avocat est très compétent."},
    {"word": "Ingénieur", "meaning": "Engineer", "example": "Il travaille comme ingénieur."},
    {"word": "Policier", "meaning": "Police officer", "example": "Le policier aide les gens."},
    {"word": "Pompier", "meaning": "Firefighter", "example": "Les pompiers sont arrivés vite."},
    {"word": "Serveur", "meaning": "Waiter", "example": "Le serveur apporte le menu."},
    {"word": "Cuisinier", "meaning": "Cook / Chef", "example": "Ce cuisinier est excellent."},
    {"word": "Boulanger", "meaning": "Baker", "example": "Le boulanger prépare le pain."},
    {"word": "Artiste", "meaning": "Artist", "example": "Cet artiste peint très bien."},
    {"word": "Écrivain", "meaning": "Writer", "example": "Cet écrivain est célèbre."},
    {"word": "Musicien", "meaning": "Musician", "example": "Le musicien joue du piano."},
    {"word": "Chanteur", "meaning": "Singer", "example": "Ce chanteur a une belle voix."},
    {"word": "Acteur", "meaning": "Actor", "example": "Cet acteur est très connu."},
    {"word": "Pilote", "meaning": "Pilot", "example": "Le pilote conduit l'avion."},
    {"word": "Chauffeur", "meaning": "Driver", "example": "Le chauffeur attend dehors."},
    {"word": "Vendeur", "meaning": "Salesperson", "example": "Le vendeur est très aimable."},
    {"word": "Client", "meaning": "Customer", "example": "Le client est satisfait."},
    {"word": "Patron", "meaning": "Boss", "example": "Mon patron est exigeant."},
    {"word": "Employé", "meaning": "Employee", "example": "Cet employé travaille dur."},
    {"word": "Jardinier", "meaning": "Gardener", "example": "Le jardinier plante des fleurs."},
    {"word": "Fermier", "meaning": "Farmer", "example": "Le fermier a des vaches."},
    {"word": "Pêcheur", "meaning": "Fisherman", "example": "Le pêcheur est au bord de la mer."},
    {"word": "Journaliste", "meaning": "Journalist", "example": "Ce journaliste écrit bien."},
    {"word": "Photographe", "meaning": "Photographer", "example": "Le photographe prend des photos."},
    {"word": "Mécanicien", "meaning": "Mechanic", "example": "Le mécanicien répare ma voiture."},
    {"word": "Coiffeur", "meaning": "Hairdresser", "example": "Je vais chez le coiffeur."},
    {"word": "Caissier", "meaning": "Cashier", "example": "Le caissier encaisse l'argent."},
    {"word": "Étranger", "meaning": "Foreigner / Abroad", "example": "Il est étranger en France."},
    {"word": "Adolescent", "meaning": "Teenager", "example": "Cet adolescent étudie bien."},
    {"word": "Adulte", "meaning": "Adult", "example": "Il est adulte maintenant."},
    {"word": "Vieux", "meaning": "Old (person)", "example": "Ce vieux monsieur est très gentil."},
    {"word": "Jeune", "meaning": "Young (person)", "example": "Ce jeune homme est poli."},
    {"word": "Jumeau", "meaning": "Twin", "example": "Les jumeaux se ressemblent."},

    # ===== FOOD & DRINK (261-360) =====
    {"word": "Nourriture", "meaning": "Food", "example": "J'aime la nourriture française."},
    {"word": "Repas", "meaning": "Meal", "example": "Le repas est délicieux."},
    {"word": "Petit déjeuner", "meaning": "Breakfast", "example": "Je prends mon petit déjeuner à sept heures."},
    {"word": "Déjeuner", "meaning": "Lunch", "example": "Le déjeuner est à midi."},
    {"word": "Dîner", "meaning": "Dinner", "example": "Le dîner est prêt."},
    {"word": "Pain", "meaning": "Bread", "example": "J'achète du pain frais."},
    {"word": "Baguette", "meaning": "Baguette", "example": "Une baguette, s'il vous plaît."},
    {"word": "Croissant", "meaning": "Croissant", "example": "Je mange un croissant au petit déjeuner."},
    {"word": "Fromage", "meaning": "Cheese", "example": "La France produit beaucoup de fromage."},
    {"word": "Beurre", "meaning": "Butter", "example": "Je mets du beurre sur le pain."},
    {"word": "Lait", "meaning": "Milk", "example": "Je bois du lait chaud."},
    {"word": "Crème", "meaning": "Cream", "example": "Je prends un café avec de la crème."},
    {"word": "Yaourt", "meaning": "Yogurt", "example": "Ce yaourt est délicieux."},
    {"word": "Œuf", "meaning": "Egg", "example": "Je mange deux œufs au petit déjeuner."},
    {"word": "Viande", "meaning": "Meat", "example": "Je ne mange pas de viande."},
    {"word": "Poulet", "meaning": "Chicken", "example": "Le poulet rôti est excellent."},
    {"word": "Bœuf", "meaning": "Beef", "example": "Le bœuf est très tendre."},
    {"word": "Porc", "meaning": "Pork", "example": "Le porc est une viande blanche."},
    {"word": "Jambon", "meaning": "Ham", "example": "Un sandwich au jambon, s'il vous plaît."},
    {"word": "Poisson", "meaning": "Fish", "example": "Le poisson est frais aujourd'hui."},
    {"word": "Saumon", "meaning": "Salmon", "example": "J'aime le saumon grillé."},
    {"word": "Légume", "meaning": "Vegetable", "example": "Mange tes légumes !"},
    {"word": "Fruit", "meaning": "Fruit", "example": "Les fruits sont bons pour la santé."},
    {"word": "Pomme", "meaning": "Apple", "example": "Je mange une pomme."},
    {"word": "Poire", "meaning": "Pear", "example": "Cette poire est sucrée."},
    {"word": "Banane", "meaning": "Banana", "example": "J'aime les bananes."},
    {"word": "Orange", "meaning": "Orange", "example": "Je bois du jus d'orange."},
    {"word": "Citron", "meaning": "Lemon", "example": "Le citron est acide."},
    {"word": "Fraise", "meaning": "Strawberry", "example": "Les fraises sont mûres."},
    {"word": "Cerise", "meaning": "Cherry", "example": "Ces cerises sont délicieuses."},
    {"word": "Raisin", "meaning": "Grape", "example": "J'aime le raisin blanc."},
    {"word": "Tomate", "meaning": "Tomato", "example": "La tomate est rouge."},
    {"word": "Pomme de terre", "meaning": "Potato", "example": "Je mange des pommes de terre."},
    {"word": "Carotte", "meaning": "Carrot", "example": "Les carottes sont bonnes pour les yeux."},
    {"word": "Oignon", "meaning": "Onion", "example": "L'oignon me fait pleurer."},
    {"word": "Ail", "meaning": "Garlic", "example": "Il y a de l'ail dans la sauce."},
    {"word": "Salade", "meaning": "Salad / Lettuce", "example": "Je prépare une salade verte."},
    {"word": "Riz", "meaning": "Rice", "example": "Le riz est cuit."},
    {"word": "Pâtes", "meaning": "Pasta", "example": "J'adore les pâtes italiennes."},
    {"word": "Soupe", "meaning": "Soup", "example": "La soupe est chaude."},
    {"word": "Sandwich", "meaning": "Sandwich", "example": "Je mange un sandwich à midi."},
    {"word": "Fromage blanc", "meaning": "Cottage cheese", "example": "Le fromage blanc est léger."},
    {"word": "Sucre", "meaning": "Sugar", "example": "Je prends du sucre dans mon café."},
    {"word": "Sel", "meaning": "Salt", "example": "Ajoute un peu de sel."},
    {"word": "Poivre", "meaning": "Pepper", "example": "Le poivre noir est fort."},
    {"word": "Huile", "meaning": "Oil", "example": "Mets de l'huile dans la poêle."},
    {"word": "Vinaigre", "meaning": "Vinegar", "example": "Le vinaigre donne du goût."},
    {"word": "Miel", "meaning": "Honey", "example": "Le miel est bon pour la gorge."},
    {"word": "Confiture", "meaning": "Jam", "example": "J'aime la confiture de fraises."},
    {"word": "Chocolat", "meaning": "Chocolate", "example": "Le chocolat chaud est délicieux."},
    {"word": "Bonbon", "meaning": "Candy", "example": "L'enfant veut un bonbon."},
    {"word": "Gâteau", "meaning": "Cake", "example": "Le gâteau d'anniversaire est prêt."},
    {"word": "Tarte", "meaning": "Pie / Tart", "example": "La tarte aux pommes est bonne."},
    {"word": "Biscuit", "meaning": "Cookie / Biscuit", "example": "Je mange un biscuit avec le thé."},
    {"word": "Glace", "meaning": "Ice cream", "example": "Les enfants adorent la glace."},
    {"word": "Café", "meaning": "Coffee", "example": "Je bois un café le matin."},
    {"word": "Thé", "meaning": "Tea", "example": "Elle boit du thé vert."},
    {"word": "Jus", "meaning": "Juice", "example": "Je prends un jus de fruit."},
    {"word": "Eau", "meaning": "Water", "example": "Je bois beaucoup d'eau."},
    {"word": "Vin", "meaning": "Wine", "example": "Ce vin rouge est excellent."},
    {"word": "Bière", "meaning": "Beer", "example": "Il commande une bière."},
    {"word": "Verre", "meaning": "Glass", "example": "Je bois un verre d'eau."},
    {"word": "Tasse", "meaning": "Cup", "example": "La tasse est pleine de café."},
    {"word": "Assiette", "meaning": "Plate", "example": "L'assiette est propre."},
    {"word": "Fourchette", "meaning": "Fork", "example": "Il me manque une fourchette."},
    {"word": "Cuillère", "meaning": "Spoon", "example": "Je mange la soupe avec une cuillère."},
    {"word": "Couteau", "meaning": "Knife", "example": "Le couteau est bien aiguisé."},
    {"word": "Serviette", "meaning": "Napkin / Towel", "example": "Passe-moi une serviette."},
    {"word": "Bouteille", "meaning": "Bottle", "example": "Il y a une bouteille sur la table."},
    {"word": "Restaurant", "meaning": "Restaurant", "example": "Ce restaurant est excellent."},
    {"word": "Menu", "meaning": "Menu", "example": "Le menu est sur la table."},
    {"word": "Addition", "meaning": "Bill", "example": "L'addition, s'il vous plaît."},
    {"word": "Pourboire", "meaning": "Tip", "example": "Il laisse un bon pourboire."},
    {"word": "Recette", "meaning": "Recipe", "example": "Cette recette est facile."},
    {"word": "Cuisine", "meaning": "Cooking / Kitchen", "example": "J'aime la cuisine italienne."},
    {"word": "Délicieux", "meaning": "Delicious", "example": "Ce plat est délicieux."},
    {"word": "Sucré", "meaning": "Sweet", "example": "Ce gâteau est trop sucré."},
    {"word": "Salé", "meaning": "Salty", "example": "La soupe est trop salée."},
    {"word": "Amer", "meaning": "Bitter", "example": "Le café noir est amer."},
    {"word": "Acide", "meaning": "Sour", "example": "Le citron est acide."},
    {"word": "Épicé", "meaning": "Spicy", "example": "Ce plat est très épicé."},
    {"word": "Chaud", "meaning": "Hot", "example": "Le thé est très chaud."},
    {"word": "Froid", "meaning": "Cold", "example": "L'eau est froide."},
    {"word": "Frais", "meaning": "Fresh", "example": "Le poisson est frais."},
    {"word": "Cru", "meaning": "Raw", "example": "Je mange des légumes crus."},
    {"word": "Cuit", "meaning": "Cooked", "example": "La viande est bien cuite."},
    {"word": "Grillé", "meaning": "Grilled", "example": "Le poulet grillé est bon."},
    {"word": "Rôti", "meaning": "Roasted", "example": "Le rôti de bœuf est prêt."},
    {"word": "Frit", "meaning": "Fried", "example": "Les frites sont frites à l'huile."},
    {"word": "Manger dehors", "meaning": "To eat out", "example": "Ce soir, nous mangeons dehors."},
    {"word": "Avoir faim", "meaning": "To be hungry", "example": "J'ai très faim."},
    {"word": "Avoir soif", "meaning": "To be thirsty", "example": "J'ai soif, je veux de l'eau."},
    {"word": "Bon appétit", "meaning": "Enjoy your meal", "example": "Bon appétit à tous !"},

    # ===== ANIMALS (361-420) =====
    {"word": "Animal", "meaning": "Animal", "example": "Cet animal est sauvage."},
    {"word": "Chien", "meaning": "Dog", "example": "Le chien aboie."},
    {"word": "Chat", "meaning": "Cat", "example": "Le chat dort sur le canapé."},
    {"word": "Cheval", "meaning": "Horse", "example": "Ce cheval est très beau."},
    {"word": "Vache", "meaning": "Cow", "example": "La vache donne du lait."},
    {"word": "Mouton", "meaning": "Sheep", "example": "Les moutons sont dans le pré."},
    {"word": "Chèvre", "meaning": "Goat", "example": "La chèvre mange l'herbe."},
    {"word": "Cochon", "meaning": "Pig", "example": "Le cochon est dans la ferme."},
    {"word": "Poule", "meaning": "Hen", "example": "La poule pond des œufs."},
    {"word": "Canard", "meaning": "Duck", "example": "Le canard nage dans l'étang."},
    {"word": "Oiseau", "meaning": "Bird", "example": "L'oiseau chante le matin."},
    {"word": "Aigle", "meaning": "Eagle", "example": "L'aigle vole haut dans le ciel."},
    {"word": "Papillon", "meaning": "Butterfly", "example": "Le papillon est coloré."},
    {"word": "Abeille", "meaning": "Bee", "example": "L'abeille fait du miel."},
    {"word": "Fourmi", "meaning": "Ant", "example": "Les fourmis travaillent dur."},
    {"word": "Araignée", "meaning": "Spider", "example": "J'ai peur des araignées."},
    {"word": "Serpent", "meaning": "Snake", "example": "Ce serpent est dangereux."},
    {"word": "Lapin", "meaning": "Rabbit", "example": "Le lapin mange une carotte."},
    {"word": "Souris", "meaning": "Mouse", "example": "La souris est petite."},
    {"word": "Renard", "meaning": "Fox", "example": "Le renard est rusé."},
    {"word": "Loup", "meaning": "Wolf", "example": "Le loup vit dans la forêt."},
    {"word": "Ours", "meaning": "Bear", "example": "L'ours dort en hiver."},
    {"word": "Lion", "meaning": "Lion", "example": "Le lion est le roi des animaux."},
    {"word": "Tigre", "meaning": "Tiger", "example": "Le tigre est très fort."},
    {"word": "Éléphant", "meaning": "Elephant", "example": "L'éléphant est énorme."},
    {"word": "Girafe", "meaning": "Giraffe", "example": "La girafe a un long cou."},
    {"word": "Singe", "meaning": "Monkey", "example": "Le singe grimpe aux arbres."},
    {"word": "Dauphin", "meaning": "Dolphin", "example": "Le dauphin est intelligent."},
    {"word": "Baleine", "meaning": "Whale", "example": "La baleine est le plus grand animal."},
    {"word": "Requin", "meaning": "Shark", "example": "Le requin est dangereux."},
    {"word": "Poisson rouge", "meaning": "Goldfish", "example": "Le poisson rouge nage dans le bocal."},
    {"word": "Tortue", "meaning": "Turtle", "example": "La tortue marche lentement."},
    {"word": "Grenouille", "meaning": "Frog", "example": "La grenouille saute."},
    {"word": "Pingouin", "meaning": "Penguin", "example": "Le pingouin vit au froid."},
    {"word": "Panda", "meaning": "Panda", "example": "Le panda mange du bambou."},
    {"word": "Kangourou", "meaning": "Kangaroo", "example": "Le kangourou saute haut."},
    {"word": "Zèbre", "meaning": "Zebra", "example": "Le zèbre a des rayures."},
    {"word": "Cerf", "meaning": "Deer", "example": "Le cerf court vite."},
    {"word": "Hibou", "meaning": "Owl", "example": "Le hibou dort le jour."},
    {"word": "Perroquet", "meaning": "Parrot", "example": "Le perroquet répète les mots."},
    {"word": "Mouche", "meaning": "Fly", "example": "La mouche vole autour de moi."},
    {"word": "Moustique", "meaning": "Mosquito", "example": "Le moustique m'a piqué."},
    {"word": "Escargot", "meaning": "Snail", "example": "L'escargot est très lent."},
    {"word": "Crabe", "meaning": "Crab", "example": "Le crabe marche de côté."},
    {"word": "Crevette", "meaning": "Shrimp", "example": "Les crevettes sont délicieuses."},
    {"word": "Pieuvre", "meaning": "Octopus", "example": "La pieuvre a huit bras."},
    {"word": "Rat", "meaning": "Rat", "example": "Ce rat est énorme."},
    {"word": "Chameau", "meaning": "Camel", "example": "Le chameau vit dans le désert."},
    {"word": "Lama", "meaning": "Llama", "example": "Le lama vient d'Amérique du Sud."},
    {"word": "Biche", "meaning": "Doe", "example": "La biche est très timide."},
    {"word": "Taureau", "meaning": "Bull", "example": "Le taureau est fort."},
    {"word": "Coq", "meaning": "Rooster", "example": "Le coq chante le matin."},
    {"word": "Poussin", "meaning": "Chick", "example": "Le poussin est jaune."},
    {"word": "Veau", "meaning": "Calf", "example": "Le veau reste près de sa mère."},
    {"word": "Agneau", "meaning": "Lamb", "example": "L'agneau est tout blanc."},
    {"word": "Poulain", "meaning": "Foal", "example": "Le poulain court dans le pré."},
    {"word": "Chiot", "meaning": "Puppy", "example": "Le chiot est mignon."},
    {"word": "Chaton", "meaning": "Kitten", "example": "Le chaton joue avec la laine."},
    {"word": "Animal de compagnie", "meaning": "Pet", "example": "Mon animal de compagnie est un chat."},
    {"word": "Animal sauvage", "meaning": "Wild animal", "example": "Le lion est un animal sauvage."},

    # ===== NATURE & WEATHER (421-480) =====
    {"word": "Nature", "meaning": "Nature", "example": "J'aime la nature."},
    {"word": "Arbre", "meaning": "Tree", "example": "Cet arbre est très vieux."},
    {"word": "Fleur", "meaning": "Flower", "example": "Cette fleur sent bon."},
    {"word": "Rose", "meaning": "Rose", "example": "La rose rouge est belle."},
    {"word": "Herbe", "meaning": "Grass", "example": "L'herbe est verte."},
    {"word": "Feuille", "meaning": "Leaf", "example": "La feuille tombe en automne."},
    {"word": "Forêt", "meaning": "Forest", "example": "Nous marchons dans la forêt."},
    {"word": "Jardin", "meaning": "Garden", "example": "Le jardin est fleuri."},
    {"word": "Champ", "meaning": "Field", "example": "Le champ est plein de blé."},
    {"word": "Montagne", "meaning": "Mountain", "example": "La montagne est haute."},
    {"word": "Colline", "meaning": "Hill", "example": "La colline est verdoyante."},
    {"word": "Vallée", "meaning": "Valley", "example": "La vallée est magnifique."},
    {"word": "Rivière", "meaning": "River", "example": "La rivière coule doucement."},
    {"word": "Fleuve", "meaning": "Large river", "example": "Le fleuve traverse la ville."},
    {"word": "Lac", "meaning": "Lake", "example": "Le lac est calme."},
    {"word": "Mer", "meaning": "Sea", "example": "La mer est bleue."},
    {"word": "Océan", "meaning": "Ocean", "example": "L'océan est immense."},
    {"word": "Plage", "meaning": "Beach", "example": "Nous allons à la plage."},
    {"word": "Île", "meaning": "Island", "example": "Cette île est déserte."},
    {"word": "Désert", "meaning": "Desert", "example": "Le désert est chaud."},
    {"word": "Terre", "meaning": "Earth / Land", "example": "La terre est ronde."},
    {"word": "Sable", "meaning": "Sand", "example": "Le sable est chaud."},
    {"word": "Pierre", "meaning": "Stone", "example": "Cette pierre est lourde."},
    {"word": "Roche", "meaning": "Rock", "example": "La roche est dure."},
    {"word": "Ciel", "meaning": "Sky", "example": "Le ciel est bleu aujourd'hui."},
    {"word": "Soleil", "meaning": "Sun", "example": "Le soleil brille."},
    {"word": "Lune", "meaning": "Moon", "example": "La lune éclaire la nuit."},
    {"word": "Étoile", "meaning": "Star", "example": "Les étoiles brillent."},
    {"word": "Nuage", "meaning": "Cloud", "example": "Le ciel est couvert de nuages."},
    {"word": "Pluie", "meaning": "Rain", "example": "La pluie tombe fort."},
    {"word": "Neige", "meaning": "Snow", "example": "La neige couvre la montagne."},
    {"word": "Vent", "meaning": "Wind", "example": "Le vent souffle fort."},
    {"word": "Orage", "meaning": "Storm", "example": "Il y a un orage ce soir."},
    {"word": "Tonnerre", "meaning": "Thunder", "example": "Le tonnerre gronde."},
    {"word": "Éclair", "meaning": "Lightning", "example": "L'éclair illumine le ciel."},
    {"word": "Brouillard", "meaning": "Fog", "example": "Le brouillard est épais."},
    {"word": "Glace", "meaning": "Ice", "example": "La glace est froide."},
    {"word": "Feu", "meaning": "Fire", "example": "Le feu brûle dans la cheminée."},
    {"word": "Air", "meaning": "Air", "example": "L'air est pur ici."},
    {"word": "Saison", "meaning": "Season", "example": "Chaque saison a son charme."},
    {"word": "Printemps", "meaning": "Spring", "example": "Au printemps, les fleurs poussent."},
    {"word": "Été", "meaning": "Summer", "example": "En été, il fait chaud."},
    {"word": "Automne", "meaning": "Autumn", "example": "En automne, les feuilles tombent."},
    {"word": "Hiver", "meaning": "Winter", "example": "En hiver, il neige."},
    {"word": "Climat", "meaning": "Climate", "example": "Le climat change."},
    {"word": "Temps", "meaning": "Weather / Time", "example": "Quel temps fait-il ?"},
    {"word": "Chaleur", "meaning": "Heat", "example": "La chaleur est insupportable."},
    {"word": "Soleil levant", "meaning": "Sunrise", "example": "Le soleil levant est magnifique."},
    {"word": "Coucher de soleil", "meaning": "Sunset", "example": "Le coucher de soleil est beau."},
    {"word": "Aube", "meaning": "Dawn", "example": "Il se lève à l'aube."},
    {"word": "Crépuscule", "meaning": "Dusk", "example": "Le crépuscule arrive."},
    {"word": "Environnement", "meaning": "Environment", "example": "Protégeons l'environnement."},
    {"word": "Pollution", "meaning": "Pollution", "example": "La pollution est un problème."},
    {"word": "Écologie", "meaning": "Ecology", "example": "L'écologie est importante."},
    {"word": "Recyclage", "meaning": "Recycling", "example": "Le recyclage aide la planète."},
    {"word": "Naturel", "meaning": "Natural", "example": "Ce produit est naturel."},
    {"word": "Sauvage", "meaning": "Wild", "example": "Cet animal est sauvage."},
    {"word": "Végétal", "meaning": "Plant-based", "example": "J'aime les produits végétaux."},
    {"word": "Animal", "meaning": "Animal", "example": "Cet animal est protégé."},

    # ===== BODY PARTS (481-540) =====
    {"word": "Corps", "meaning": "Body", "example": "Le corps humain est complexe."},
    {"word": "Tête", "meaning": "Head", "example": "J'ai mal à la tête."},
    {"word": "Visage", "meaning": "Face", "example": "Son visage est souriant."},
    {"word": "Œil", "meaning": "Eye", "example": "J'ai les yeux bleus."},
    {"word": "Yeux", "meaning": "Eyes", "example": "Ses yeux sont verts."},
    {"word": "Nez", "meaning": "Nose", "example": "J'ai le nez qui coule."},
    {"word": "Bouche", "meaning": "Mouth", "example": "Ouvre la bouche."},
    {"word": "Lèvre", "meaning": "Lip", "example": "Ses lèvres sont rouges."},
    {"word": "Dent", "meaning": "Tooth", "example": "Je me brosse les dents."},
    {"word": "Langue", "meaning": "Tongue", "example": "Tire la langue."},
    {"word": "Oreille", "meaning": "Ear", "example": "J'ai mal à l'oreille."},
    {"word": "Cou", "meaning": "Neck", "example": "J'ai mal au cou."},
    {"word": "Épaule", "meaning": "Shoulder", "example": "Il a mal à l'épaule."},
    {"word": "Bras", "meaning": "Arm", "example": "Lève les bras."},
    {"word": "Main", "meaning": "Hand", "example": "Lave-toi les mains."},
    {"word": "Doigt", "meaning": "Finger", "example": "Je me suis coupé le doigt."},
    {"word": "Ongle", "meaning": "Nail", "example": "Elle se coupe les ongles."},
    {"word": "Poitrine", "meaning": "Chest", "example": "Il a mal à la poitrine."},
    {"word": "Ventre", "meaning": "Belly", "example": "Mon ventre gargouille."},
    {"word": "Dos", "meaning": "Back", "example": "J'ai mal au dos."},
    {"word": "Jambe", "meaning": "Leg", "example": "Il s'est cassé la jambe."},
    {"word": "Genou", "meaning": "Knee", "example": "J'ai mal au genou."},
    {"word": "Pied", "meaning": "Foot", "example": "J'ai mal aux pieds."},
    {"word": "Orteil", "meaning": "Toe", "example": "Je me suis cogné l'orteil."},
    {"word": "Peau", "meaning": "Skin", "example": "Sa peau est douce."},
    {"word": "Cheveux", "meaning": "Hair", "example": "Elle a de longs cheveux."},
    {"word": "Barbe", "meaning": "Beard", "example": "Il a une belle barbe."},
    {"word": "Sang", "meaning": "Blood", "example": "Il y a du sang."},
    {"word": "Cœur", "meaning": "Heart", "example": "Mon cœur bat vite."},
    {"word": "Poumon", "meaning": "Lung", "example": "Fumer nuit aux poumons."},
    {"word": "Foie", "meaning": "Liver", "example": "Le foie est un organe."},
    {"word": "Estomac", "meaning": "Stomach", "example": "J'ai mal à l'estomac."},
    {"word": "Cerveau", "meaning": "Brain", "example": "Le cerveau contrôle le corps."},
    {"word": "Os", "meaning": "Bone", "example": "Le chien ronge un os."},
    {"word": "Muscle", "meaning": "Muscle", "example": "Il a de bons muscles."},
    {"word": "Santé", "meaning": "Health", "example": "La santé est importante."},
    {"word": "Maladie", "meaning": "Illness", "example": "Cette maladie est grave."},
    {"word": "Fièvre", "meaning": "Fever", "example": "Il a de la fièvre."},
    {"word": "Rhume", "meaning": "Cold", "example": "J'ai attrapé un rhume."},
    {"word": "Grippe", "meaning": "Flu", "example": "Elle a la grippe."},
    {"word": "Toux", "meaning": "Cough", "example": "Il a une toux sèche."},
    {"word": "Douleur", "meaning": "Pain", "example": "Cette douleur est forte."},
    {"word": "Blessure", "meaning": "Wound", "example": "Sa blessure guérit."},
    {"word": "Médicament", "meaning": "Medicine", "example": "Prends ton médicament."},
    {"word": "Comprimé", "meaning": "Pill", "example": "Avale un comprimé."},
    {"word": "Ordonnance", "meaning": "Prescription", "example": "Le médecin écrit une ordonnance."},
    {"word": "Hôpital", "meaning": "Hospital", "example": "Elle travaille à l'hôpital."},
    {"word": "Pharmacie", "meaning": "Pharmacy", "example": "Je vais à la pharmacie."},
    {"word": "Urgence", "meaning": "Emergency", "example": "C'est une urgence."},
    {"word": "Ambulance", "meaning": "Ambulance", "example": "L'ambulance arrive vite."},
    {"word": "Repos", "meaning": "Rest", "example": "Prends du repos."},
    {"word": "Sommeil", "meaning": "Sleep", "example": "Le sommeil est essentiel."},
    {"word": "Rêve", "meaning": "Dream", "example": "J'ai fait un beau rêve."},
    {"word": "Fatigue", "meaning": "Fatigue", "example": "Je ressens de la fatigue."},
    {"word": "Énergie", "meaning": "Energy", "example": "J'ai beaucoup d'énergie."},
    {"word": "Sport", "meaning": "Sport", "example": "Je fais du sport."},
    {"word": "Exercice", "meaning": "Exercise", "example": "L'exercice est bon pour la santé."},
    {"word": "Marche", "meaning": "Walk", "example": "Je fais une marche chaque jour."},
    {"word": "Course", "meaning": "Running", "example": "La course me détend."},
    {"word": "Médecin", "meaning": "Doctor", "example": "Je vais chez le médecin."},

    # ===== HOUSE & OBJECTS (541-640) =====
    {"word": "Maison", "meaning": "House", "example": "Ma maison est grande."},
    {"word": "Appartement", "meaning": "Apartment", "example": "J'habite dans un appartement."},
    {"word": "Chambre", "meaning": "Bedroom", "example": "Ma chambre est propre."},
    {"word": "Cuisine", "meaning": "Kitchen", "example": "La cuisine est bien équipée."},
    {"word": "Salon", "meaning": "Living room", "example": "Nous regardons la télé dans le salon."},
    {"word": "Salle de bain", "meaning": "Bathroom", "example": "La salle de bain est petite."},
    {"word": "Porte", "meaning": "Door", "example": "Ferme la porte."},
    {"word": "Fenêtre", "meaning": "Window", "example": "Ouvre la fenêtre."},
    {"word": "Mur", "meaning": "Wall", "example": "Le mur est blanc."},
    {"word": "Sol", "meaning": "Floor", "example": "Le sol est propre."},
    {"word": "Plafond", "meaning": "Ceiling", "example": "Le plafond est haut."},
    {"word": "Toit", "meaning": "Roof", "example": "Le toit est rouge."},
    {"word": "Escalier", "meaning": "Stairs", "example": "Monte les escaliers."},
    {"word": "Jardin", "meaning": "Garden", "example": "Le jardin est fleuri."},
    {"word": "Balcon", "meaning": "Balcony", "example": "Le balcon donne sur la rue."},
    {"word": "Garage", "meaning": "Garage", "example": "La voiture est au garage."},
    {"word": "Meuble", "meaning": "Furniture", "example": "Ces meubles sont modernes."},
    {"word": "Table", "meaning": "Table", "example": "La table est en bois."},
    {"word": "Chaise", "meaning": "Chair", "example": "Assieds-toi sur la chaise."},
    {"word": "Lit", "meaning": "Bed", "example": "Mon lit est confortable."},
    {"word": "Canapé", "meaning": "Sofa", "example": "Le canapé est doux."},
    {"word": "Armoire", "meaning": "Wardrobe", "example": "Mes vêtements sont dans l'armoire."},
    {"word": "Étagère", "meaning": "Shelf", "example": "Les livres sont sur l'étagère."},
    {"word": "Bureau", "meaning": "Desk", "example": "Mon bureau est encombré."},
    {"word": "Lampe", "meaning": "Lamp", "example": "Allume la lampe."},
    {"word": "Miroir", "meaning": "Mirror", "example": "Je me regarde dans le miroir."},
    {"word": "Tapis", "meaning": "Carpet", "example": "Le tapis est rouge."},
    {"word": "Rideau", "meaning": "Curtain", "example": "Ferme les rideaux."},
    {"word": "Oreiller", "meaning": "Pillow", "example": "Cet oreiller est moelleux."},
    {"word": "Couverture", "meaning": "Blanket", "example": "La couverture est chaude."},
    {"word": "Clé", "meaning": "Key", "example": "J'ai perdu mes clés."},
    {"word": "Serrure", "meaning": "Lock", "example": "La serrure est cassée."},
    {"word": "Verre", "meaning": "Glass (drinking)", "example": "Je bois un verre d'eau."},
    {"word": "Bouteille", "meaning": "Bottle", "example": "La bouteille est vide."},
    {"word": "Casserole", "meaning": "Pan", "example": "La casserole est sur le feu."},
    {"word": "Four", "meaning": "Oven", "example": "Le four est préchauffé."},
    {"word": "Réfrigérateur", "meaning": "Refrigerator", "example": "Le lait est dans le réfrigérateur."},
    {"word": "Lave-vaisselle", "meaning": "Dishwasher", "example": "Le lave-vaisselle est en marche."},
    {"word": "Machine à laver", "meaning": "Washing machine", "example": "La machine à laver est pleine."},
    {"word": "Télévision", "meaning": "Television", "example": "Nous regardons la télévision."},
    {"word": "Téléphone", "meaning": "Telephone", "example": "Mon téléphone sonne."},
    {"word": "Ordinateur", "meaning": "Computer", "example": "J'utilise mon ordinateur."},
    {"word": "Clavier", "meaning": "Keyboard", "example": "Le clavier est neuf."},
    {"word": "Souris", "meaning": "Mouse (computer)", "example": "La souris ne marche pas."},
    {"word": "Écran", "meaning": "Screen", "example": "L'écran est grand."},
    {"word": "Livre", "meaning": "Book", "example": "Je lis un livre."},
    {"word": "Cahier", "meaning": "Notebook", "example": "Mon cahier est propre."},
    {"word": "Stylo", "meaning": "Pen", "example": "Peux-tu me prêter un stylo ?"},
    {"word": "Crayon", "meaning": "Pencil", "example": "J'écris avec un crayon."},
    {"word": "Gomme", "meaning": "Eraser", "example": "Passe-moi la gomme."},
    {"word": "Règle", "meaning": "Ruler", "example": "La règle mesure trente centimètres."},
    {"word": "Papier", "meaning": "Paper", "example": "Donne-moi du papier."},
    {"word": "Journal", "meaning": "Newspaper", "example": "Je lis le journal."},
    {"word": "Carte", "meaning": "Card / Map", "example": "Regarde la carte."},
    {"word": "Sac", "meaning": "Bag", "example": "Mon sac est lourd."},
    {"word": "Valise", "meaning": "Suitcase", "example": "Ma valise est prête."},
    {"word": "Portefeuille", "meaning": "Wallet", "example": "Mon portefeuille est vide."},
    {"word": "Montre", "meaning": "Watch", "example": "Ma montre est en retard."},
    {"word": "Bague", "meaning": "Ring", "example": "Elle porte une belle bague."},
    {"word": "Collier", "meaning": "Necklace", "example": "Ce collier est en or."},
    {"word": "Lunettes", "meaning": "Glasses", "example": "Je porte des lunettes."},
    {"word": "Chapeau", "meaning": "Hat", "example": "Il porte un chapeau."},
    {"word": "Chaussure", "meaning": "Shoe", "example": "Mes chaussures sont neuves."},
    {"word": "Chemise", "meaning": "Shirt", "example": "Cette chemise est blanche."},
    {"word": "Pantalon", "meaning": "Pants", "example": "Mon pantalon est bleu."},
    {"word": "Robe", "meaning": "Dress", "example": "Elle porte une robe rouge."},
    {"word": "Manteau", "meaning": "Coat", "example": "Mon manteau est chaud."},
    {"word": "Veste", "meaning": "Jacket", "example": "Ma veste est en cuir."},

    # ===== PLACES & TRAVEL (641-720) =====
    {"word": "Ville", "meaning": "City", "example": "Paris est une belle ville."},
    {"word": "Village", "meaning": "Village", "example": "Ce village est calme."},
    {"word": "Capitale", "meaning": "Capital", "example": "Paris est la capitale de la France."},
    {"word": "Quartier", "meaning": "Neighborhood", "example": "J'habite dans un bon quartier."},
    {"word": "Rue", "meaning": "Street", "example": "Cette rue est animée."},
    {"word": "Avenue", "meaning": "Avenue", "example": "L'avenue est large."},
    {"word": "Boulevard", "meaning": "Boulevard", "example": "Le boulevard est bruyant."},
    {"word": "Place", "meaning": "Square", "example": "La place est grande."},
    {"word": "Route", "meaning": "Road", "example": "La route est longue."},
    {"word": "Chemin", "meaning": "Path", "example": "Le chemin est étroit."},
    {"word": "Pont", "meaning": "Bridge", "example": "Le pont traverse la rivière."},
    {"word": "Carrefour", "meaning": "Intersection", "example": "Tourne au carrefour."},
    {"word": "Trottoir", "meaning": "Sidewalk", "example": "Marche sur le trottoir."},
    {"word": "Magasin", "meaning": "Shop", "example": "Ce magasin est ouvert."},
    {"word": "Boutique", "meaning": "Boutique", "example": "Cette boutique est chic."},
    {"word": "Marché", "meaning": "Market", "example": "Le marché est le samedi."},
    {"word": "Supermarché", "meaning": "Supermarket", "example": "Je vais au supermarché."},
    {"word": "Boulangerie", "meaning": "Bakery", "example": "J'achète du pain à la boulangerie."},
    {"word": "Boucherie", "meaning": "Butcher shop", "example": "La boucherie est fermée."},
    {"word": "Pharmacie", "meaning": "Pharmacy", "example": "La pharmacie est ouverte."},
    {"word": "École", "meaning": "School", "example": "Les enfants vont à l'école."},
    {"word": "Université", "meaning": "University", "example": "Elle étudie à l'université."},
    {"word": "Bibliothèque", "meaning": "Library", "example": "Je vais à la bibliothèque."},
    {"word": "Musée", "meaning": "Museum", "example": "Ce musée est intéressant."},
    {"word": "Théâtre", "meaning": "Theater", "example": "Le théâtre est plein."},
    {"word": "Cinéma", "meaning": "Cinema", "example": "Nous allons au cinéma."},
    {"word": "Restaurant", "meaning": "Restaurant", "example": "Ce restaurant est bondé."},
    {"word": "Café", "meaning": "Cafe", "example": "On se retrouve au café."},
    {"word": "Bar", "meaning": "Bar", "example": "Le bar est bruyant."},
    {"word": "Hôtel", "meaning": "Hotel", "example": "L'hôtel est confortable."},
    {"word": "Banque", "meaning": "Bank", "example": "Je vais à la banque."},
    {"word": "Poste", "meaning": "Post office", "example": "La poste est fermée."},
    {"word": "Gare", "meaning": "Train station", "example": "Le train part de la gare."},
    {"word": "Aéroport", "meaning": "Airport", "example": "L'avion décolle de l'aéroport."},
    {"word": "Port", "meaning": "Harbor", "example": "Le port est animé."},
    {"word": "Parking", "meaning": "Parking lot", "example": "Le parking est gratuit."},
    {"word": "Église", "meaning": "Church", "example": "L'église est ancienne."},
    {"word": "Mosquée", "meaning": "Mosque", "example": "La mosquée est belle."},
    {"word": "Château", "meaning": "Castle", "example": "Ce château est magnifique."},
    {"word": "Monument", "meaning": "Monument", "example": "Ce monument est célèbre."},
    {"word": "Tour", "meaning": "Tower", "example": "La tour Eiffel est haute."},
    {"word": "Parc", "meaning": "Park", "example": "Le parc est vert."},
    {"word": "Plage", "meaning": "Beach", "example": "La plage est bondée."},
    {"word": "Piscine", "meaning": "Pool", "example": "La piscine est ouverte."},
    {"word": "Stade", "meaning": "Stadium", "example": "Le stade est plein."},
    {"word": "Voyage", "meaning": "Trip / Journey", "example": "Bon voyage !"},
    {"word": "Vacances", "meaning": "Vacation", "example": "Je pars en vacances."},
    {"word": "Tourisme", "meaning": "Tourism", "example": "Le tourisme est important."},
    {"word": "Touriste", "meaning": "Tourist", "example": "Les touristes visitent Paris."},
    {"word": "Guide", "meaning": "Guide", "example": "Le guide explique tout."},
    {"word": "Boussole", "meaning": "Compass", "example": "Utilise une boussole."},
    {"word": "Direction", "meaning": "Direction", "example": "Va dans cette direction."},
    {"word": "Nord", "meaning": "North", "example": "Le nord est froid."},
    {"word": "Sud", "meaning": "South", "example": "Le sud est chaud."},
    {"word": "Est", "meaning": "East", "example": "L'est est montagneux."},
    {"word": "Ouest", "meaning": "West", "example": "L'ouest est pluvieux."},
    {"word": "Gauche", "meaning": "Left", "example": "Tourne à gauche."},
    {"word": "Droite", "meaning": "Right", "example": "Tourne à droite."},
    {"word": "Tout droit", "meaning": "Straight ahead", "example": "Continue tout droit."},
    {"word": "Loin", "meaning": "Far", "example": "C'est très loin d'ici."},
    {"word": "Près", "meaning": "Near", "example": "La gare est près d'ici."},
    {"word": "Ici", "meaning": "Here", "example": "Viens ici."},
    {"word": "Là", "meaning": "There", "example": "Pose-le là."},
    {"word": "Bagages", "meaning": "Luggage", "example": "Mes bagages sont lourds."},
    {"word": "Billet", "meaning": "Ticket", "example": "J'ai acheté deux billets."},
    {"word": "Réservation", "meaning": "Reservation", "example": "J'ai une réservation."},
    {"word": "Passeport", "meaning": "Passport", "example": "Montre ton passeport."},
    {"word": "Avion", "meaning": "Airplane", "example": "L'avion est en retard."},
    {"word": "Train", "meaning": "Train", "example": "Le train arrive à midi."},
    {"word": "Bus", "meaning": "Bus", "example": "Je prends le bus."},
    {"word": "Métro", "meaning": "Subway", "example": "Le métro est rapide."},
    {"word": "Taxi", "meaning": "Taxi", "example": "Appelons un taxi."},
    {"word": "Voiture", "meaning": "Car", "example": "Ma voiture est rouge."},
    {"word": "Vélo", "meaning": "Bicycle", "example": "Je vais au travail en vélo."},
    {"word": "Moto", "meaning": "Motorcycle", "example": "Il conduit une moto."},
    {"word": "Camion", "meaning": "Truck", "example": "Le camion est lourd."},
    {"word": "Bateau", "meaning": "Boat", "example": "Le bateau flotte."},
    {"word": "Essence", "meaning": "Gasoline", "example": "La voiture manque d'essence."},
    {"word": "Pneu", "meaning": "Tire", "example": "Le pneu est crevé."},
    {"word": "Volant", "meaning": "Steering wheel", "example": "Il tourne le volant."},
    {"word": "Frein", "meaning": "Brake", "example": "Appuie sur le frein."},
    {"word": "Moteur", "meaning": "Engine", "example": "Le moteur fait du bruit."},

    # ===== TIME & NUMBERS (721-800) =====
    {"word": "Temps", "meaning": "Time", "example": "Le temps passe vite."},
    {"word": "Heure", "meaning": "Hour", "example": "Quelle heure est-il ?"},
    {"word": "Minute", "meaning": "Minute", "example": "Attends une minute."},
    {"word": "Seconde", "meaning": "Second", "example": "Une seconde, je viens."},
    {"word": "Matin", "meaning": "Morning", "example": "Le matin, je bois du café."},
    {"word": "Après-midi", "meaning": "Afternoon", "example": "Cet après-midi, je travaille."},
    {"word": "Soir", "meaning": "Evening", "example": "Le soir, je lis."},
    {"word": "Nuit", "meaning": "Night", "example": "Bonne nuit !"},
    {"word": "Aujourd'hui", "meaning": "Today", "example": "Aujourd'hui, il fait beau."},
    {"word": "Hier", "meaning": "Yesterday", "example": "Hier, j'ai vu Marie."},
    {"word": "Demain", "meaning": "Tomorrow", "example": "Demain, je pars."},
    {"word": "Maintenant", "meaning": "Now", "example": "Viens maintenant."},
    {"word": "Bientôt", "meaning": "Soon", "example": "Il arrive bientôt."},
    {"word": "Tôt", "meaning": "Early", "example": "Je me lève tôt."},
    {"word": "Tard", "meaning": "Late", "example": "Il est tard."},
    {"word": "Toujours", "meaning": "Always", "example": "Il est toujours en retard."},
    {"word": "Jamais", "meaning": "Never", "example": "Je ne mens jamais."},
    {"word": "Souvent", "meaning": "Often", "example": "Je voyage souvent."},
    {"word": "Parfois", "meaning": "Sometimes", "example": "Parfois, il pleut."},
    {"word": "Rarement", "meaning": "Rarely", "example": "Il vient rarement."},
    {"word": "Encore", "meaning": "Again / Still", "example": "Encore une fois !"},
    {"word": "Déjà", "meaning": "Already", "example": "Je l'ai déjà vu."},
    {"word": "Enfin", "meaning": "Finally", "example": "Enfin, tu es là !"},
    {"word": "Jour", "meaning": "Day", "example": "Chaque jour est nouveau."},
    {"word": "Semaine", "meaning": "Week", "example": "La semaine prochaine, je pars."},
    {"word": "Mois", "meaning": "Month", "example": "Le mois de mai est agréable."},
    {"word": "Année", "meaning": "Year", "example": "Bonne année !"},
    {"word": "Siècle", "meaning": "Century", "example": "Ce siècle est moderne."},
    {"word": "Lundi", "meaning": "Monday", "example": "Lundi, je travaille."},
    {"word": "Mardi", "meaning": "Tuesday", "example": "Mardi, j'ai rendez-vous."},
    {"word": "Mercredi", "meaning": "Wednesday", "example": "Mercredi, je fais du sport."},
    {"word": "Jeudi", "meaning": "Thursday", "example": "Jeudi, c'est mon anniversaire."},
    {"word": "Vendredi", "meaning": "Friday", "example": "Vendredi soir, c'est la fête."},
    {"word": "Samedi", "meaning": "Saturday", "example": "Samedi, je me repose."},
    {"word": "Dimanche", "meaning": "Sunday", "example": "Dimanche, c'est repos."},
    {"word": "Janvier", "meaning": "January", "example": "Janvier est froid."},
    {"word": "Février", "meaning": "February", "example": "Février est court."},
    {"word": "Mars", "meaning": "March", "example": "Mars annonce le printemps."},
    {"word": "Avril", "meaning": "April", "example": "Avril est pluvieux."},
    {"word": "Mai", "meaning": "May", "example": "Mai est fleuri."},
    {"word": "Juin", "meaning": "June", "example": "Juin est chaud."},
    {"word": "Juillet", "meaning": "July", "example": "Juillet, c'est les vacances."},
    {"word": "Août", "meaning": "August", "example": "Août est très chaud."},
    {"word": "Septembre", "meaning": "September", "example": "Septembre, c'est la rentrée."},
    {"word": "Octobre", "meaning": "October", "example": "Octobre est coloré."},
    {"word": "Novembre", "meaning": "November", "example": "Novembre est gris."},
    {"word": "Décembre", "meaning": "December", "example": "Décembre, c'est Noël."},
    {"word": "Un", "meaning": "One", "example": "J'ai un chat."},
    {"word": "Deux", "meaning": "Two", "example": "J'ai deux frères."},
    {"word": "Trois", "meaning": "Three", "example": "Il y a trois pommes."},
    {"word": "Quatre", "meaning": "Four", "example": "Quatre saisons."},
    {"word": "Cinq", "meaning": "Five", "example": "Cinq doigts par main."},
    {"word": "Six", "meaning": "Six", "example": "Six heures du matin."},
    {"word": "Sept", "meaning": "Seven", "example": "Sept jours dans une semaine."},
    {"word": "Huit", "meaning": "Eight", "example": "Huit heures du soir."},
    {"word": "Neuf", "meaning": "Nine", "example": "Neuf mois de grossesse."},
    {"word": "Dix", "meaning": "Ten", "example": "Dix euros."},
    {"word": "Onze", "meaning": "Eleven", "example": "Onze joueurs dans une équipe."},
    {"word": "Douze", "meaning": "Twelve", "example": "Douze mois dans une année."},
    {"word": "Vingt", "meaning": "Twenty", "example": "Vingt personnes."},
    {"word": "Trente", "meaning": "Thirty", "example": "Trente jours dans un mois."},
    {"word": "Quarante", "meaning": "Forty", "example": "Quarante ans."},
    {"word": "Cinquante", "meaning": "Fifty", "example": "Cinquante centimes."},
    {"word": "Soixante", "meaning": "Sixty", "example": "Soixante minutes dans une heure."},
    {"word": "Cent", "meaning": "Hundred", "example": "Cent euros."},
    {"word": "Mille", "meaning": "Thousand", "example": "Mille mercis."},
    {"word": "Million", "meaning": "Million", "example": "Un million d'euros."},
    {"word": "Premier", "meaning": "First", "example": "Je suis le premier."},
    {"word": "Deuxième", "meaning": "Second", "example": "Le deuxième étage."},
    {"word": "Troisième", "meaning": "Third", "example": "La troisième fois."},
    {"word": "Dernier", "meaning": "Last", "example": "C'est la dernière fois."},
    {"word": "Prochain", "meaning": "Next", "example": "La prochaine fois."},
    {"word": "Début", "meaning": "Beginning", "example": "Le début de l'histoire."},
    {"word": "Fin", "meaning": "End", "example": "La fin du film."},
    {"word": "Moment", "meaning": "Moment", "example": "Un moment, s'il vous plaît."},
    {"word": "Date", "meaning": "Date", "example": "Quelle est la date ?"},
    {"word": "Rendez-vous", "meaning": "Appointment / Date", "example": "J'ai un rendez-vous."},

    # ===== COLORS & ADJECTIVES (801-900) =====
    {"word": "Couleur", "meaning": "Color", "example": "Quelle est ta couleur préférée ?"},
    {"word": "Rouge", "meaning": "Red", "example": "La pomme est rouge."},
    {"word": "Bleu", "meaning": "Blue", "example": "Le ciel est bleu."},
    {"word": "Vert", "meaning": "Green", "example": "L'herbe est verte."},
    {"word": "Jaune", "meaning": "Yellow", "example": "Le soleil est jaune."},
    {"word": "Orange", "meaning": "Orange", "example": "Cette orange est sucrée."},
    {"word": "Violet", "meaning": "Purple", "example": "Elle porte une robe violette."},
    {"word": "Rose", "meaning": "Pink", "example": "Cette fleur est rose."},
    {"word": "Marron", "meaning": "Brown", "example": "Ses cheveux sont marron."},
    {"word": "Noir", "meaning": "Black", "example": "Le chat est noir."},
    {"word": "Blanc", "meaning": "White", "example": "La neige est blanche."},
    {"word": "Gris", "meaning": "Gray", "example": "Le ciel est gris."},
    {"word": "Doré", "meaning": "Golden", "example": "Cette bague est dorée."},
    {"word": "Grand", "meaning": "Big / Tall", "example": "Cet homme est grand."},
    {"word": "Petit", "meaning": "Small", "example": "Cet enfant est petit."},
    {"word": "Gros", "meaning": "Fat / Big", "example": "Ce sac est gros."},
    {"word": "Long", "meaning": "Long", "example": "Ce chemin est long."},
    {"word": "Court", "meaning": "Short", "example": "Ce film est court."},
    {"word": "Haut", "meaning": "High / Tall", "example": "Cette montagne est haute."},
    {"word": "Bas", "meaning": "Low", "example": "Cette table est basse."},
    {"word": "Large", "meaning": "Wide", "example": "Cette rue est large."},
    {"word": "Étroit", "meaning": "Narrow", "example": "Ce passage est étroit."},
    {"word": "Épais", "meaning": "Thick", "example": "Ce livre est épais."},
    {"word": "Mince", "meaning": "Thin", "example": "Elle est très mince."},
    {"word": "Lourd", "meaning": "Heavy", "example": "Ce sac est lourd."},
    {"word": "Léger", "meaning": "Light (weight)", "example": "Cette valise est légère."},
    {"word": "Plein", "meaning": "Full", "example": "Le verre est plein."},
    {"word": "Vide", "meaning": "Empty", "example": "La bouteille est vide."},
    {"word": "Chaud", "meaning": "Hot", "example": "Le café est chaud."},
    {"word": "Froid", "meaning": "Cold", "example": "La glace est froide."},
    {"word": "Doux", "meaning": "Soft / Sweet", "example": "Ce coussin est doux."},
    {"word": "Dur", "meaning": "Hard", "example": "Ce pain est dur."},
    {"word": "Lisse", "meaning": "Smooth", "example": "Cette pierre est lisse."},
    {"word": "Vieux", "meaning": "Old", "example": "Ce livre est vieux."},
    {"word": "Jeune", "meaning": "Young", "example": "Elle est jeune."},
    {"word": "Nouveau", "meaning": "New", "example": "J'ai un nouveau téléphone."},
    {"word": "Beau", "meaning": "Beautiful", "example": "Ce tableau est beau."},
    {"word": "Joli", "meaning": "Pretty", "example": "Cette robe est jolie."},
    {"word": "Laid", "meaning": "Ugly", "example": "Ce bâtiment est laid."},
    {"word": "Bon", "meaning": "Good", "example": "Ce gâteau est bon."},
    {"word": "Mauvais", "meaning": "Bad", "example": "Le temps est mauvais."},
    {"word": "Excellent", "meaning": "Excellent", "example": "Ce repas est excellent."},
    {"word": "Parfait", "meaning": "Perfect", "example": "Ton travail est parfait."},
    {"word": "Content", "meaning": "Happy", "example": "Je suis content de te voir."},
    {"word": "Heureux", "meaning": "Happy", "example": "Il est très heureux."},
    {"word": "Triste", "meaning": "Sad", "example": "Elle est triste aujourd'hui."},
    {"word": "Fatigué", "meaning": "Tired", "example": "Je suis fatigué."},
    {"word": "Malade", "meaning": "Sick", "example": "Mon frère est malade."},
    {"word": "Fort", "meaning": "Strong", "example": "Il est très fort."},
    {"word": "Faible", "meaning": "Weak", "example": "Cette lampe est faible."},
    {"word": "Riche", "meaning": "Rich", "example": "Cet homme est riche."},
    {"word": "Pauvre", "meaning": "Poor", "example": "Cette famille est pauvre."},
    {"word": "Célèbre", "meaning": "Famous", "example": "C'est un acteur célèbre."},
    {"word": "Facile", "meaning": "Easy", "example": "Cet exercice est facile."},
    {"word": "Difficile", "meaning": "Difficult", "example": "Ce problème est difficile."},
    {"word": "Simple", "meaning": "Simple", "example": "La solution est simple."},
    {"word": "Compliqué", "meaning": "Complicated", "example": "Cette histoire est compliquée."},
    {"word": "Propre", "meaning": "Clean", "example": "La chambre est propre."},
    {"word": "Sale", "meaning": "Dirty", "example": "Mes chaussures sont sales."},
    {"word": "Ouvert", "meaning": "Open", "example": "Le magasin est ouvert."},
    {"word": "Fermé", "meaning": "Closed", "example": "La porte est fermée."},
    {"word": "Vrai", "meaning": "True", "example": "C'est une vraie histoire."},
    {"word": "Faux", "meaning": "False", "example": "C'est un faux billet."},
    {"word": "Même", "meaning": "Same", "example": "Nous avons le même âge."},
    {"word": "Différent", "meaning": "Different", "example": "Ces deux livres sont différents."},
    {"word": "Autre", "meaning": "Other", "example": "Prends un autre stylo."},
    {"word": "Prêt", "meaning": "Ready", "example": "Je suis prêt."},
    {"word": "Occupé", "meaning": "Busy", "example": "Il est occupé."},
    {"word": "Libre", "meaning": "Free", "example": "Cette place est libre."},
    {"word": "Utile", "meaning": "Useful", "example": "Ce dictionnaire est utile."},
    {"word": "Important", "meaning": "Important", "example": "C'est important."},
    {"word": "Possible", "meaning": "Possible", "example": "C'est possible."},
    {"word": "Impossible", "meaning": "Impossible", "example": "C'est impossible."},
    {"word": "Sûr", "meaning": "Sure", "example": "Es-tu sûr ?"},
    {"word": "Clair", "meaning": "Clear / Light", "example": "C'est très clair."},
    {"word": "Sombre", "meaning": "Dark", "example": "La chambre est sombre."},
    {"word": "Lumineux", "meaning": "Bright", "example": "Cet appartement est lumineux."},
    {"word": "Délicieux", "meaning": "Delicious", "example": "Ce gâteau est délicieux."},
    {"word": "Étrange", "meaning": "Strange", "example": "C'est étrange."},
    {"word": "Normal", "meaning": "Normal", "example": "C'est normal."},
    {"word": "Génial", "meaning": "Great", "example": "C'est génial !"},
    {"word": "Magnifique", "meaning": "Magnificent", "example": "Ce paysage est magnifique."},
    {"word": "Horrible", "meaning": "Horrible", "example": "C'est horrible !"},
    {"word": "Sympathique", "meaning": "Nice", "example": "Il est sympathique."},
    {"word": "Gentil", "meaning": "Kind", "example": "Elle est gentille."},
    {"word": "Méchant", "meaning": "Mean", "example": "Ne sois pas méchant."},
    {"word": "Poli", "meaning": "Polite", "example": "Cet enfant est poli."},
    {"word": "Honnête", "meaning": "Honest", "example": "C'est un homme honnête."},
    {"word": "Intelligent", "meaning": "Intelligent", "example": "Elle est intelligente."},
    {"word": "Bête", "meaning": "Stupid", "example": "Ne fais pas le bête."},
    {"word": "Sage", "meaning": "Wise / Well-behaved", "example": "Ce vieil homme est sage."},
    {"word": "Calme", "meaning": "Calm", "example": "La mer est calme."},
    {"word": "Timide", "meaning": "Shy", "example": "Il est timide."},
    {"word": "Généreux", "meaning": "Generous", "example": "Tu es généreux."},
    {"word": "Patient", "meaning": "Patient", "example": "Sois patient."},
    {"word": "Curieux", "meaning": "Curious", "example": "Cet enfant est curieux."},
    {"word": "Optimiste", "meaning": "Optimistic", "example": "Elle est optimiste."},
    {"word": "Pessimiste", "meaning": "Pessimistic", "example": "Ne sois pas pessimiste."},

    # ===== EMOTIONS & FEELINGS (901-940) =====
    {"word": "Amour", "meaning": "Love", "example": "L'amour est beau."},
    {"word": "Amitié", "meaning": "Friendship", "example": "Notre amitié est forte."},
    {"word": "Bonheur", "meaning": "Happiness", "example": "Le bonheur est simple."},
    {"word": "Tristesse", "meaning": "Sadness", "example": "Il y a de la tristesse."},
    {"word": "Joie", "meaning": "Joy", "example": "Quelle joie de te voir !"},
    {"word": "Peur", "meaning": "Fear", "example": "J'ai peur du noir."},
    {"word": "Colère", "meaning": "Anger", "example": "Il est en colère."},
    {"word": "Surprise", "meaning": "Surprise", "example": "Quelle belle surprise !"},
    {"word": "Espoir", "meaning": "Hope", "example": "L'espoir fait vivre."},
    {"word": "Rêve", "meaning": "Dream", "example": "J'ai fait un rêve."},
    {"word": "Pensée", "meaning": "Thought", "example": "Mes pensées sont pour toi."},
    {"word": "Idée", "meaning": "Idea", "example": "J'ai une idée."},
    {"word": "Mémoire", "meaning": "Memory", "example": "J'ai une bonne mémoire."},
    {"word": "Vérité", "meaning": "Truth", "example": "Dis-moi la vérité."},
    {"word": "Mensonge", "meaning": "Lie", "example": "Ne dis pas de mensonge."},
    {"word": "Secret", "meaning": "Secret", "example": "Garde le secret."},
    {"word": "Silence", "meaning": "Silence", "example": "Le silence est d'or."},
    {"word": "Paix", "meaning": "Peace", "example": "Vive la paix."},
    {"word": "Guerre", "meaning": "War", "example": "La guerre est terrible."},
    {"word": "Liberté", "meaning": "Freedom", "example": "La liberté est un droit."},
    {"word": "Justice", "meaning": "Justice", "example": "La justice est importante."},
    {"word": "Pouvoir", "meaning": "Power", "example": "Le pouvoir corrompt."},
    {"word": "Force", "meaning": "Strength", "example": "Il a de la force."},
    {"word": "Courage", "meaning": "Courage", "example": "Bon courage !"},
    {"word": "Sagesse", "meaning": "Wisdom", "example": "La sagesse vient avec l'âge."},
    {"word": "Talent", "meaning": "Talent", "example": "Elle a du talent."},
    {"word": "Travail", "meaning": "Work", "example": "J'aime mon travail."},
    {"word": "Succès", "meaning": "Success", "example": "Ce fut un grand succès."},
    {"word": "Échec", "meaning": "Failure", "example": "L'échec fait apprendre."},
    {"word": "Effort", "meaning": "Effort", "example": "Fais un effort."},
    {"word": "Vie", "meaning": "Life", "example": "La vie est belle."},
    {"word": "Mort", "meaning": "Death", "example": "La mort fait partie de la vie."},
    {"word": "Naissance", "meaning": "Birth", "example": "La naissance d'un enfant."},
    {"word": "Jeunesse", "meaning": "Youth", "example": "La jeunesse est belle."},
    {"word": "Santé", "meaning": "Health", "example": "La santé est importante."},
    {"word": "Beauté", "meaning": "Beauty", "example": "La beauté est dans le cœur."},
    {"word": "Art", "meaning": "Art", "example": "L'art est éternel."},
    {"word": "Culture", "meaning": "Culture", "example": "J'aime la culture française."},
    {"word": "Science", "meaning": "Science", "example": "La science progresse."},
    {"word": "Philosophie", "meaning": "Philosophy", "example": "La philosophie aide à penser."},

    # ===== COMMON ADVERBS (941-990) =====
    {"word": "Très", "meaning": "Very", "example": "C'est très bien."},
    {"word": "Trop", "meaning": "Too much", "example": "C'est trop cher."},
    {"word": "Assez", "meaning": "Enough", "example": "J'en ai assez."},
    {"word": "Peu", "meaning": "Little / Few", "example": "J'ai peu de temps."},
    {"word": "Beaucoup", "meaning": "A lot", "example": "J'aime beaucoup ça."},
    {"word": "Plus", "meaning": "More", "example": "Il en faut plus."},
    {"word": "Moins", "meaning": "Less", "example": "Il y en a moins."},
    {"word": "Aussi", "meaning": "Also / Too", "example": "Moi aussi."},
    {"word": "Bien", "meaning": "Well", "example": "Tu parles bien français."},
    {"word": "Mal", "meaning": "Badly", "example": "Je dors mal."},
    {"word": "Mieux", "meaning": "Better", "example": "Ça va mieux."},
    {"word": "Surtout", "meaning": "Especially", "example": "Surtout, ne bouge pas."},
    {"word": "Sauf", "meaning": "Except", "example": "Tout le monde sauf lui."},
    {"word": "Selon", "meaning": "According to", "example": "Selon moi, c'est vrai."},
    {"word": "Malgré", "meaning": "Despite", "example": "Malgré la pluie, je sors."},
    {"word": "Pendant", "meaning": "During", "example": "Pendant l'été, il fait chaud."},
    {"word": "Depuis", "meaning": "Since", "example": "Depuis hier, je suis ici."},
    {"word": "Après", "meaning": "After", "example": "Après toi."},
    {"word": "Avant", "meaning": "Before", "example": "Avant tout."},
    {"word": "Avec", "meaning": "With", "example": "Viens avec moi."},
    {"word": "Sans", "meaning": "Without", "example": "Sans toi, je ne peux pas."},
    {"word": "Pour", "meaning": "For", "example": "Ce cadeau est pour toi."},
    {"word": "Contre", "meaning": "Against", "example": "Je suis contre cette idée."},
    {"word": "Sur", "meaning": "On", "example": "Le livre est sur la table."},
    {"word": "Sous", "meaning": "Under", "example": "Le chat est sous le lit."},
    {"word": "Dans", "meaning": "In", "example": "Je suis dans la maison."},
    {"word": "Chez", "meaning": "At (someone's place)", "example": "Je vais chez Marie."},
    {"word": "Vers", "meaning": "Towards", "example": "Il va vers la gare."},
    {"word": "Entre", "meaning": "Between", "example": "Entre toi et moi."},
    {"word": "Devant", "meaning": "In front of", "example": "Devant la maison."},
    {"word": "Derrière", "meaning": "Behind", "example": "Derrière la porte."},
    {"word": "Ici", "meaning": "Here", "example": "Viens ici."},
    {"word": "Là", "meaning": "There", "example": "Pose-le là."},
    {"word": "Partout", "meaning": "Everywhere", "example": "Il y en a partout."},
    {"word": "Dedans", "meaning": "Inside", "example": "Rentre dedans."},
    {"word": "Dehors", "meaning": "Outside", "example": "Va jouer dehors."},
    {"word": "Alors", "meaning": "Then / So", "example": "Alors, on y va ?"},
    {"word": "Donc", "meaning": "Therefore", "example": "Je pense, donc je suis."},
    {"word": "Ainsi", "meaning": "Thus", "example": "Ainsi va la vie."},
    {"word": "Pourtant", "meaning": "However", "example": "Pourtant, c'est vrai."},
    {"word": "Cependant", "meaning": "However", "example": "Cependant, il faut essayer."},
    {"word": "Enfin", "meaning": "Finally", "example": "Enfin, te voilà !"},
    {"word": "En fait", "meaning": "In fact", "example": "En fait, je ne sais pas."},
    {"word": "D'ailleurs", "meaning": "Moreover", "example": "D'ailleurs, tu as raison."},
    {"word": "Sinon", "meaning": "Otherwise", "example": "Sinon, on rentre."},
    {"word": "Ensemble", "meaning": "Together", "example": "Faisons-le ensemble."},
    {"word": "Seul", "meaning": "Alone", "example": "Je suis seul."},
    {"word": "Vite", "meaning": "Fast", "example": "Viens vite !"},
    {"word": "Lentement", "meaning": "Slowly", "example": "Parle lentement."},
    {"word": "Doucement", "meaning": "Gently", "example": "Vas-y doucement."},
    {"word": "Facilement", "meaning": "Easily", "example": "Il réussit facilement."},

    # ===== ABSTRACT NOUNS & MISC (991-1080) =====
    {"word": "Chose", "meaning": "Thing", "example": "Chaque chose en son temps."},
    {"word": "Endroit", "meaning": "Place", "example": "C'est un bel endroit."},
    {"word": "Lieu", "meaning": "Location", "example": "Le lieu du rendez-vous."},
    {"word": "Exemple", "meaning": "Example", "example": "Par exemple, moi."},
    {"word": "Problème", "meaning": "Problem", "example": "Quel est le problème ?"},
    {"word": "Solution", "meaning": "Solution", "example": "J'ai la solution."},
    {"word": "Question", "meaning": "Question", "example": "J'ai une question."},
    {"word": "Réponse", "meaning": "Answer", "example": "Ta réponse est bonne."},
    {"word": "Sujet", "meaning": "Subject / Topic", "example": "Changeons de sujet."},
    {"word": "Mot", "meaning": "Word", "example": "Ce mot est difficile."},
    {"word": "Phrase", "meaning": "Sentence", "example": "Cette phrase est correcte."},
    {"word": "Texte", "meaning": "Text", "example": "Lis ce texte."},
    {"word": "Page", "meaning": "Page", "example": "Tourne la page."},
    {"word": "Chapitre", "meaning": "Chapter", "example": "Chapitre premier."},
    {"word": "Partie", "meaning": "Part", "example": "C'est la meilleure partie."},
    {"word": "Liste", "meaning": "List", "example": "Fais une liste."},
    {"word": "Ligne", "meaning": "Line", "example": "Trace une ligne."},
    {"word": "Forme", "meaning": "Shape / Form", "example": "En bonne forme."},
    {"word": "Taille", "meaning": "Size", "example": "Quelle taille fais-tu ?"},
    {"word": "Poids", "meaning": "Weight", "example": "Quel est ton poids ?"},
    {"word": "Nombre", "meaning": "Number", "example": "Un grand nombre de gens."},
    {"word": "Quantité", "meaning": "Quantity", "example": "La quantité importe peu."},
    {"word": "Qualité", "meaning": "Quality", "example": "La qualité prime."},
    {"word": "Type", "meaning": "Type", "example": "Quel type de musique ?"},
    {"word": "Genre", "meaning": "Kind / Gender", "example": "Ce genre de film."},
    {"word": "Catégorie", "meaning": "Category", "example": "Chaque catégorie a sa place."},
    {"word": "Classe", "meaning": "Class", "example": "Ma classe est grande."},
    {"word": "Groupe", "meaning": "Group", "example": "Un groupe de touristes."},
    {"word": "Équipe", "meaning": "Team", "example": "Notre équipe a gagné."},
    {"word": "Collection", "meaning": "Collection", "example": "Il a une belle collection."},
    {"word": "Série", "meaning": "Series", "example": "Cette série est bien."},
    {"word": "Bord", "meaning": "Edge", "example": "Au bord de la mer."},
    {"word": "Coin", "meaning": "Corner", "example": "Au coin de la rue."},
    {"word": "Centre", "meaning": "Center", "example": "Au centre-ville."},
    {"word": "Côté", "meaning": "Side", "example": "De ce côté."},
    {"word": "Face", "meaning": "Face / Side", "example": "Face à face."},
    {"word": "Intérieur", "meaning": "Interior", "example": "À l'intérieur."},
    {"word": "Extérieur", "meaning": "Exterior", "example": "À l'extérieur."},
    {"word": "Entrée", "meaning": "Entry", "example": "L'entrée est gratuite."},
    {"word": "Sortie", "meaning": "Exit", "example": "La sortie est là."},
    {"word": "Moyen", "meaning": "Means / Way", "example": "Trouve un moyen."},
    {"word": "Manière", "meaning": "Manner", "example": "De cette manière."},
    {"word": "Façon", "meaning": "Way", "example": "De toute façon."},
    {"word": "Méthode", "meaning": "Method", "example": "Cette méthode marche."},
    {"word": "Système", "meaning": "System", "example": "Le système est complexe."},
    {"word": "Développement", "meaning": "Development", "example": "Le développement durable."},
    {"word": "Croissance", "meaning": "Growth", "example": "La croissance est forte."},
    {"word": "Évolution", "meaning": "Evolution", "example": "L'évolution est constante."},
    {"word": "Changement", "meaning": "Change", "example": "Un grand changement."},
    {"word": "Mouvement", "meaning": "Movement", "example": "Un mouvement de foule."},
    {"word": "Action", "meaning": "Action", "example": "Passons à l'action."},
    {"word": "Résultat", "meaning": "Result", "example": "Le résultat est bon."},
    {"word": "Cause", "meaning": "Cause", "example": "À cause de la pluie."},
    {"word": "Effet", "meaning": "Effect", "example": "L'effet est immédiat."},
    {"word": "But", "meaning": "Goal", "example": "Quel est ton but ?"},
    {"word": "Objectif", "meaning": "Objective", "example": "Notre objectif est clair."},
    {"word": "Projet", "meaning": "Project", "example": "J'ai un nouveau projet."},
    {"word": "Plan", "meaning": "Plan", "example": "Suivons le plan."},
    {"word": "Opinion", "meaning": "Opinion", "example": "Ton opinion compte."},
    {"word": "Avis", "meaning": "Opinion", "example": "À mon avis, c'est bon."},
    {"word": "Réalité", "meaning": "Reality", "example": "La réalité est dure."},
    {"word": "Doute", "meaning": "Doubt", "example": "J'ai un doute."},
    {"word": "Preuve", "meaning": "Proof", "example": "Donne-moi une preuve."},
    {"word": "Témoin", "meaning": "Witness", "example": "Le témoin a parlé."},
    {"word": "Accident", "meaning": "Accident", "example": "Il y a eu un accident."},
    {"word": "Événement", "meaning": "Event", "example": "C'est un grand événement."},
    {"word": "Fête", "meaning": "Party / Holiday", "example": "Bonne fête !"},
    {"word": "Célébration", "meaning": "Celebration", "example": "La célébration commence."},
    {"word": "Mariage", "meaning": "Wedding", "example": "Leur mariage est en juin."},
    {"word": "Anniversaire", "meaning": "Birthday", "example": "Joyeux anniversaire !"},
    {"word": "Noël", "meaning": "Christmas", "example": "Joyeux Noël !"},
    {"word": "Vacances", "meaning": "Vacation", "example": "Bonnes vacances !"},
    {"word": "Week-end", "meaning": "Weekend", "example": "Bon week-end !"},
    {"word": "Congé", "meaning": "Leave", "example": "Je suis en congé."},
    {"word": "Emploi", "meaning": "Job", "example": "Il cherche un emploi."},
    {"word": "Poste", "meaning": "Position", "example": "J'ai un nouveau poste."},
    {"word": "Salaire", "meaning": "Salary", "example": "Son salaire est bon."},
    {"word": "Impôt", "meaning": "Tax", "example": "Je paye mes impôts."},
    {"word": "Facture", "meaning": "Bill", "example": "Voici la facture."},
    {"word": "Monnaie", "meaning": "Currency / Change", "example": "Rends-moi la monnaie."},
    {"word": "Argent", "meaning": "Money / Silver", "example": "Je n'ai pas d'argent."},
    {"word": "Prix", "meaning": "Price", "example": "Quel est le prix ?"},
    {"word": "Coût", "meaning": "Cost", "example": "Le coût est élevé."},
    {"word": "Dépense", "meaning": "Expense", "example": "Réduis les dépenses."},
    {"word": "Revenu", "meaning": "Income", "example": "Son revenu est stable."},
    {"word": "Budget", "meaning": "Budget", "example": "Le budget est serré."},
    {"word": "Économie", "meaning": "Savings / Economy", "example": "Fais des économies."},
    {"word": "Dette", "meaning": "Debt", "example": "J'ai une dette."},
    {"word": "Crédit", "meaning": "Credit", "example": "Il a un bon crédit."},
    {"word": "Prêt", "meaning": "Loan", "example": "La banque fait un prêt."},
    {"word": "Compte", "meaning": "Account", "example": "Mon compte est vide."},
    {"word": "Chèque", "meaning": "Check", "example": "Payez par chèque."},
    {"word": "Espèces", "meaning": "Cash", "example": "Je paye en espèces."},

    # ===== USEFUL DAILY PHRASES (1081-1130) =====
    {"word": "Je ne comprends pas", "meaning": "I don't understand", "example": "Désolé, je ne comprends pas."},
    {"word": "Pouvez-vous répéter", "meaning": "Can you repeat", "example": "Pouvez-vous répéter, s'il vous plaît ?"},
    {"word": "Parlez plus lentement", "meaning": "Speak slower", "example": "Parlez plus lentement, s'il vous plaît."},
    {"word": "Comment dit-on", "meaning": "How do you say", "example": "Comment dit-on 'book' en français ?"},
    {"word": "Qu'est-ce que c'est", "meaning": "What is it", "example": "Qu'est-ce que c'est que ça ?"},
    {"word": "Où est", "meaning": "Where is", "example": "Où est la gare ?"},
    {"word": "Combien ça coûte", "meaning": "How much does it cost", "example": "Combien ça coûte ?"},
    {"word": "Je voudrais", "meaning": "I would like", "example": "Je voudrais un café."},
    {"word": "Avez-vous", "meaning": "Do you have", "example": "Avez-vous du pain ?"},
    {"word": "Je cherche", "meaning": "I'm looking for", "example": "Je cherche un hôtel."},
    {"word": "Je m'appelle", "meaning": "My name is", "example": "Je m'appelle Pierre."},
    {"word": "J'ai besoin de", "meaning": "I need", "example": "J'ai besoin d'aide."},
    {"word": "Je voudrais réserver", "meaning": "I'd like to book", "example": "Je voudrais réserver une table."},
    {"word": "C'est combien", "meaning": "How much is it", "example": "C'est combien, s'il vous plaît ?"},
    {"word": "Je suis perdu", "meaning": "I'm lost", "example": "Excusez-moi, je suis perdu."},
    {"word": "Aidez-moi", "meaning": "Help me", "example": "Aidez-moi, s'il vous plaît !"},
    {"word": "Attention", "meaning": "Careful", "example": "Attention à la voiture !"},
    {"word": "Regarde", "meaning": "Look", "example": "Regarde là-bas !"},
    {"word": "Écoute", "meaning": "Listen", "example": "Écoute bien."},
    {"word": "Viens", "meaning": "Come", "example": "Viens avec nous."},
    {"word": "Attends", "meaning": "Wait", "example": "Attends un instant."},
    {"word": "Vas-y", "meaning": "Go ahead", "example": "Vas-y, tu peux le faire !"},
    {"word": "Dépêche-toi", "meaning": "Hurry up", "example": "Dépêche-toi, on est en retard."},
    {"word": "Ne t'inquiète pas", "meaning": "Don't worry", "example": "Ne t'inquiète pas, tout va bien."},
    {"word": "Ça ne fait rien", "meaning": "It doesn't matter", "example": "Ça ne fait rien, oublie."},
    {"word": "Bien joué", "meaning": "Well done", "example": "Bien joué, félicitations !"},
    {"word": "Tant pis", "meaning": "Too bad", "example": "Tant pis, ce sera pour une autre fois."},
    {"word": "Tant mieux", "meaning": "So much the better", "example": "Tant mieux pour toi !"},
    {"word": "À mon avis", "meaning": "In my opinion", "example": "À mon avis, tu as tort."},
    {"word": "En tout cas", "meaning": "In any case", "example": "En tout cas, je viendrai."},
    {"word": "Par contre", "meaning": "On the other hand", "example": "Par contre, c'est cher."},
    {"word": "De temps en temps", "meaning": "From time to time", "example": "Je voyage de temps en temps."},
    {"word": "Tout de suite", "meaning": "Right away", "example": "Je viens tout de suite."},
    {"word": "Tout à coup", "meaning": "Suddenly", "example": "Tout à coup, il a plu."},
    {"word": "Peu à peu", "meaning": "Little by little", "example": "Peu à peu, j'apprends."},
    {"word": "Tout à l'heure", "meaning": "Later / A while ago", "example": "À tout à l'heure !"},
    {"word": "D'accord", "meaning": "Alright", "example": "D'accord, je comprends."},
    {"word": "Pas de problème", "meaning": "No problem", "example": "Pas de problème, je t'aide."},
    {"word": "Ça marche", "meaning": "That works", "example": "Ça marche, on se voit demain."},
    {"word": "Je suis d'accord", "meaning": "I agree", "example": "Je suis d'accord avec toi."},
    {"word": "Je ne suis pas d'accord", "meaning": "I disagree", "example": "Je ne suis pas d'accord du tout."},
    {"word": "Peut-être que oui", "meaning": "Maybe yes", "example": "Peut-être que oui, peut-être que non."},
    {"word": "Bien entendu", "meaning": "Of course", "example": "Bien entendu, je viendrai."},
    {"word": "Sans doute", "meaning": "Probably", "example": "Sans doute, il est en retard."},
    {"word": "Bref", "meaning": "In short", "example": "Bref, c'est compliqué."},
    {"word": "Voilà", "meaning": "There you go", "example": "Voilà, c'est fait."},
    {"word": "Voici", "meaning": "Here is", "example": "Voici mon ami."},
    {"word": "Il y a", "meaning": "There is / are", "example": "Il y a un chat sur le lit."},
    {"word": "C'est", "meaning": "It is", "example": "C'est magnifique."},
    {"word": "Ce n'est pas", "meaning": "It is not", "example": "Ce n'est pas grave."},
]

print(f"[INIT] Loaded {len(VOCAB_DATABASE)} words")

# ==========================================
# 5. MAIN PICKER
# ==========================================
def get_unique_word():
    remaining = [
        w for w in VOCAB_DATABASE
        if w["word"].lower() not in SENT_WORDS
    ]

    if remaining:
        item = random.choice(remaining)
        SENT_WORDS.add(item["word"].lower())
        save_sent_words(SENT_WORDS)
        return item["word"], item["meaning"], item["example"]

    print("[WARN] All words sent! Recycling from start.")
    item = random.choice(VOCAB_DATABASE)
    return item["word"], item["meaning"], item["example"]

# ==========================================
# 6. TELEGRAM DELIVERY
# ==========================================
async def send_word():
    bot = Bot(token=TOKEN)
    word, meaning, example = get_unique_word()

    message = (
        f"🇫🇷 <b>French Word of the Hour</b>\n\n"
        f"🗣 <b>Word:</b> {html.escape(word)}\n"
        f"💡 <b>Meaning:</b> {html.escape(meaning)}\n"
        f"📝 <b>Example:</b> <i>{html.escape(example)}</i>"
    )

    await bot.send_message(chat_id=CHAT_ID, text=message, parse_mode="HTML")
    print(f"[SENT] {word}")

def job():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(send_word())
    except Exception as e:
        print(f"[JOB ERROR] {e}")
    finally:
        loop.close()

# ==========================================
# 7. SCHEDULER
# ==========================================
def scheduler_loop():
    print("⏰ First word in 5 minutes...")
    time.sleep(300)
    job()
    print("✅ First sent. Next every 1 hour.")
    while True:
        time.sleep(3600)
        job()

threading.Thread(target=scheduler_loop, daemon=True).start()

# ==========================================
# 8. KEEP ALIVE
# ==========================================
def keep_alive():
    while True:
        time.sleep(300)
        if RENDER_URL:
            try:
                requests.get(RENDER_URL, timeout=10)
            except Exception:
                pass

threading.Thread(target=keep_alive, daemon=True).start()

# ==========================================
# 9. START
# ==========================================
if __name__ == "__main__":
    print(f"🤖 Bot initialized. {len(SENT_WORDS)} words already sent.")
    print(f"📚 Total words available: {len(VOCAB_DATABASE)}")
    while True:
        time.sleep(60)
