import os
import json
import time
import html
import random
import asyncio
import threading
import requests
from http.server import HTTPServer, BaseHTTPRequestHandler
from telegram import Bot

# ==========================================
# 1. HEALTH CHECK SERVER
# ==========================================
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Bot status: OK & Running")
    def log_message(self, format, *args):
        pass

def run_server():
    port = int(os.environ.get("PORT", 8080))
    HTTPServer(('0.0.0.0', port), HealthHandler).serve_forever()

threading.Thread(target=run_server, daemon=True).start()

# ==========================================
# 2. CONFIG
# ==========================================
TOKEN         = os.environ["BOT_TOKEN"]
CHAT_ID       = os.environ["CHAT_ID"]
RENDER_URL    = os.environ.get("RENDER_URL", "")
GIST_ID       = os.environ["GIST_ID"]
GITHUB_TOKEN  = os.environ["GITHUB_TOKEN"]

GIST_API = f"https://api.github.com/gists/{GIST_ID}"
GH_HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

# ==========================================
# 3. GIST PERSISTENCE
# ==========================================
def load_sent_words():
    try:
        r = requests.get(GIST_API, headers=GH_HEADERS, timeout=10)
        content = r.json()["files"]["sent.json"]["content"]
        data = json.loads(content)
        print(f"[GIST] Loaded {len(data)} sent words")
        return set(w.lower() for w in data)
    except Exception as e:
        print(f"[GIST] Load failed: {e}")
        return set()

def save_sent_words(sent_set):
    for attempt in range(3):
        try:
            r = requests.patch(
                GIST_API,
                headers=GH_HEADERS,
                json={"files": {"sent.json": {
                    "content": json.dumps(sorted(sent_set), ensure_ascii=False)
                }}},
                timeout=10
            )
            if r.status_code == 200:
                print(f"[GIST] Saved {len(sent_set)} words")
                return True
        except Exception as e:
            print(f"[GIST] Save error: {e}")
        time.sleep(2)
    return False

SENT_WORDS = load_sent_words()

# ==========================================
# 4. FRENCH DICTIONARY — 2000 WORDS
# ==========================================
# Format: (French word, English meaning)
WORDS_RAW = [
    # ===== GREETINGS & POLITENESS (1-60) =====
    ("Bonjour", "Hello / Good morning"),
    ("Bonsoir", "Good evening"),
    ("Salut", "Hi / Bye (informal)"),
    ("Bonne nuit", "Good night"),
    ("Au revoir", "Goodbye"),
    ("À bientôt", "See you soon"),
    ("À demain", "See you tomorrow"),
    ("À tout à l'heure", "See you later"),
    ("Merci", "Thank you"),
    ("Merci beaucoup", "Thank you very much"),
    ("Merci mille fois", "Thanks a thousand times"),
    ("De rien", "You're welcome"),
    ("Je vous en prie", "You're welcome (formal)"),
    ("S'il vous plaît", "Please (formal)"),
    ("S'il te plaît", "Please (informal)"),
    ("Pardon", "Sorry / Excuse me"),
    ("Excusez-moi", "Excuse me"),
    ("Désolé", "Sorry"),
    ("Oui", "Yes"),
    ("Non", "No"),
    ("Peut-être", "Maybe"),
    ("Bien sûr", "Of course"),
    ("D'accord", "Okay"),
    ("Pas du tout", "Not at all"),
    ("Absolument", "Absolutely"),
    ("Certainement", "Certainly"),
    ("Exactement", "Exactly"),
    ("Comment", "How"),
    ("Pourquoi", "Why"),
    ("Quand", "When"),
    ("Où", "Where"),
    ("Qui", "Who"),
    ("Quoi", "What"),
    ("Que", "What / That"),
    ("Combien", "How much"),
    ("Quel", "Which"),
    ("Quelle", "Which (feminine)"),
    ("Comment allez-vous", "How are you (formal)"),
    ("Comment vas-tu", "How are you (informal)"),
    ("Ça va", "I'm fine"),
    ("Ça va bien", "I'm doing well"),
    ("Enchanté", "Nice to meet you"),
    ("Bienvenue", "Welcome"),
    ("Félicitations", "Congratulations"),
    ("Bonne chance", "Good luck"),
    ("Santé", "Cheers / Health"),
    ("Joyeux anniversaire", "Happy birthday"),
    ("Bonne année", "Happy new year"),
    ("Joyeux Noël", "Merry Christmas"),
    ("Joyeuses Pâques", "Happy Easter"),
    ("Bonne journée", "Have a good day"),
    ("Bonne soirée", "Have a good evening"),
    ("Bon voyage", "Have a good trip"),
    ("Bon appétit", "Enjoy your meal"),
    ("Bonne route", "Have a safe trip"),
    ("Bonne chance", "Good luck"),
    ("Bonne fête", "Happy holiday"),
    ("Meilleures salutations", "Best regards"),
    ("Cordialement", "Sincerely"),
    ("Amitiés", "Best wishes"),

    # ===== COMMON VERBS (61-320) =====
    ("Être", "To be"),
    ("Avoir", "To have"),
    ("Faire", "To do / make"),
    ("Aller", "To go"),
    ("Venir", "To come"),
    ("Pouvoir", "To be able to"),
    ("Vouloir", "To want"),
    ("Devoir", "To must / have to"),
    ("Savoir", "To know (facts)"),
    ("Connaître", "To know (people)"),
    ("Voir", "To see"),
    ("Regarder", "To watch"),
    ("Entendre", "To hear"),
    ("Écouter", "To listen"),
    ("Parler", "To speak"),
    ("Dire", "To say"),
    ("Demander", "To ask"),
    ("Répondre", "To answer"),
    ("Penser", "To think"),
    ("Croire", "To believe"),
    ("Trouver", "To find"),
    ("Chercher", "To look for"),
    ("Donner", "To give"),
    ("Prendre", "To take"),
    ("Mettre", "To put"),
    ("Tenir", "To hold"),
    ("Laisser", "To leave / let"),
    ("Garder", "To keep"),
    ("Acheter", "To buy"),
    ("Vendre", "To sell"),
    ("Payer", "To pay"),
    ("Travailler", "To work"),
    ("Jouer", "To play"),
    ("Étudier", "To study"),
    ("Apprendre", "To learn"),
    ("Comprendre", "To understand"),
    ("Enseigner", "To teach"),
    ("Expliquer", "To explain"),
    ("Oublier", "To forget"),
    ("Se souvenir", "To remember"),
    ("Aimer", "To love / like"),
    ("Adorer", "To adore"),
    ("Détester", "To hate"),
    ("Préférer", "To prefer"),
    ("Espérer", "To hope"),
    ("Attendre", "To wait"),
    ("Arriver", "To arrive"),
    ("Partir", "To leave"),
    ("Rentrer", "To return home"),
    ("Rester", "To stay"),
    ("Dormir", "To sleep"),
    ("Se réveiller", "To wake up"),
    ("Se lever", "To get up"),
    ("S'asseoir", "To sit down"),
    ("Se coucher", "To go to bed"),
    ("Manger", "To eat"),
    ("Boire", "To drink"),
    ("Cuisiner", "To cook"),
    ("Goûter", "To taste"),
    ("Marcher", "To walk"),
    ("Courir", "To run"),
    ("Nager", "To swim"),
    ("Voler", "To fly / steal"),
    ("Danser", "To dance"),
    ("Chanter", "To sing"),
    ("Rire", "To laugh"),
    ("Pleurer", "To cry"),
    ("Sourire", "To smile"),
    ("Lire", "To read"),
    ("Écrire", "To write"),
    ("Dessiner", "To draw"),
    ("Peindre", "To paint"),
    ("Ouvrir", "To open"),
    ("Fermer", "To close"),
    ("Commencer", "To start"),
    ("Finir", "To finish"),
    ("Continuer", "To continue"),
    ("Arrêter", "To stop"),
    ("Changer", "To change"),
    ("Aider", "To help"),
    ("Essayer", "To try"),
    ("Réussir", "To succeed"),
    ("Échouer", "To fail"),
    ("Gagner", "To win / earn"),
    ("Perdre", "To lose"),
    ("Envoyer", "To send"),
    ("Recevoir", "To receive"),
    ("Porter", "To carry / wear"),
    ("Montrer", "To show"),
    ("Cacher", "To hide"),
    ("Construire", "To build"),
    ("Casser", "To break"),
    ("Réparer", "To repair"),
    ("Nettoyer", "To clean"),
    ("Laver", "To wash"),
    ("Coudre", "To sew"),
    ("Conduire", "To drive"),
    ("Voyager", "To travel"),
    ("Visiter", "To visit"),
    ("Rester", "To remain"),
    ("Tomber", "To fall"),
    ("Monter", "To go up"),
    ("Descendre", "To go down"),
    ("Tourner", "To turn"),
    ("Retourner", "To return"),
    ("Traverser", "To cross"),
    ("Suivre", "To follow"),
    ("Conduire", "To lead / drive"),
    ("Pousser", "To push"),
    ("Tirer", "To pull"),
    ("Lancer", "To throw"),
    ("Attraper", "To catch"),
    ("Battre", "To beat"),
    ("Toucher", "To touch"),
    ("Sentir", "To feel / smell"),
    ("Goûter", "To taste"),
    ("Regarder", "To look at"),
    ("Remarquer", "To notice"),
    ("Observer", "To observe"),
    ("Écouter", "To listen"),
    ("Entendre", "To hear"),
    ("Chuchoter", "To whisper"),
    ("Crier", "To shout"),
    ("Appeler", "To call"),
    ("Nommer", "To name"),
    ("Raconter", "To tell"),
    ("Décrire", "To describe"),
    ("Expliquer", "To explain"),
    ("Traduire", "To translate"),
    ("Signifier", "To mean"),
    ("Compter", "To count"),
    ("Mesurer", "To measure"),
    ("Peser", "To weigh"),
    ("Comparer", "To compare"),
    ("Choisir", "To choose"),
    ("Décider", "To decide"),
    ("Accepter", "To accept"),
    ("Refuser", "To refuse"),
    ("Permettre", "To allow"),
    ("Interdire", "To forbid"),
    ("Promettre", "To promise"),
    ("Mentir", "To lie"),
    ("Avouer", "To confess"),
    ("Révéler", "To reveal"),
    ("Cacher", "To hide"),
    ("Tromper", "To deceive"),
    ("Aider", "To help"),
    ("Sauver", "To save"),
    ("Protéger", "To protect"),
    ("Défendre", "To defend"),
    ("Attaquer", "To attack"),
    ("Blesser", "To hurt"),
    ("Soigner", "To treat"),
    ("Guérir", "To heal"),
    ("Souffrir", "To suffer"),
    ("Mourir", "To die"),
    ("Vivre", "To live"),
    ("Naître", "To be born"),
    ("Grandir", "To grow"),
    ("Vieillir", "To age"),
    ("Changer", "To change"),
    ("Améliorer", "To improve"),
    ("Détériorer", "To worsen"),
    ("Créer", "To create"),
    ("Détruire", "To destroy"),
    ("Inventer", "To invent"),
    ("Découvrir", "To discover"),
    ("Trouver", "To find"),
    ("Chercher", "To search"),
    ("Ranger", "To tidy"),
    ("Organiser", "To organize"),
    ("Préparer", "To prepare"),
    ("Planifier", "To plan"),
    ("Réaliser", "To achieve"),
    ("Terminer", "To complete"),
    ("Commencer", "To begin"),
    ("Reprendre", "To resume"),
    ("Poursuivre", "To pursue"),
    ("Abandonner", "To abandon"),
    ("Renoncer", "To give up"),
    ("Hésiter", "To hesitate"),
    ("Oser", "To dare"),
    ("Risquer", "To risk"),
    ("Tenter", "To attempt"),
    ("Réessayer", "To retry"),
    ("Corriger", "To correct"),
    ("Vérifier", "To verify"),
    ("Contrôler", "To check"),
    ("Surveiller", "To monitor"),
    ("Observer", "To observe"),
    ("Analyser", "To analyze"),
    ("Étudier", "To study"),
    ("Chercher", "To research"),
    ("Explorer", "To explore"),
    ("Découvrir", "To discover"),
    ("Apprendre", "To learn"),
    ("Mémoriser", "To memorize"),
    ("Répéter", "To repeat"),
    ("Réciter", "To recite"),
    ("Lire", "To read"),
    ("Écrire", "To write"),
    ("Noter", "To note"),
    ("Signer", "To sign"),
    ("Marquer", "To mark"),
    ("Souligner", "To underline"),
    ("Effacer", "To erase"),
    ("Rayer", "To cross out"),
    ("Déchirer", "To tear"),
    ("Coller", "To paste"),
    ("Couper", "To cut"),
    ("Plier", "To fold"),
    ("Envelopper", "To wrap"),
    ("Emballer", "To pack"),
    ("Déballer", "To unpack"),
    ("Ouvrir", "To open"),
    ("Fermer", "To close"),
    ("Verrouiller", "To lock"),
    ("Déverrouiller", "To unlock"),
    ("Pousser", "To push"),
    ("Tirer", "To pull"),
    ("Soulever", "To lift"),
    ("Baisser", "To lower"),
    ("Monter", "To raise"),
    ("Descendre", "To lower"),
    ("Placer", "To place"),
    ("Poser", "To put down"),
    ("Ranger", "To store"),
    ("Empiler", "To stack"),
    ("Trier", "To sort"),

    # ===== FAMILY & PEOPLE (321-450) =====
    ("Famille", "Family"),
    ("Père", "Father"),
    ("Mère", "Mother"),
    ("Papa", "Dad"),
    ("Maman", "Mom"),
    ("Parents", "Parents"),
    ("Frère", "Brother"),
    ("Sœur", "Sister"),
    ("Grand-père", "Grandfather"),
    ("Grand-mère", "Grandmother"),
    ("Grands-parents", "Grandparents"),
    ("Petit-fils", "Grandson"),
    ("Petite-fille", "Granddaughter"),
    ("Oncle", "Uncle"),
    ("Tante", "Aunt"),
    ("Cousin", "Cousin (m)"),
    ("Cousine", "Cousin (f)"),
    ("Neveu", "Nephew"),
    ("Nièce", "Niece"),
    ("Fils", "Son"),
    ("Fille", "Daughter / Girl"),
    ("Enfant", "Child"),
    ("Bébé", "Baby"),
    ("Mari", "Husband"),
    ("Femme", "Wife / Woman"),
    ("Époux", "Spouse (m)"),
    ("Épouse", "Spouse (f)"),
    ("Fiancé", "Fiancé"),
    ("Fiancée", "Fiancée"),
    ("Ami", "Friend (m)"),
    ("Amie", "Friend (f)"),
    ("Copain", "Boyfriend / Buddy"),
    ("Copine", "Girlfriend"),
    ("Voisin", "Neighbor (m)"),
    ("Voisine", "Neighbor (f)"),
    ("Collègue", "Colleague"),
    ("Camarade", "Comrade"),
    ("Patron", "Boss"),
    ("Employé", "Employee"),
    ("Client", "Client"),
    ("Homme", "Man"),
    ("Femme", "Woman"),
    ("Garçon", "Boy"),
    ("Fille", "Girl"),
    ("Monsieur", "Sir / Mr."),
    ("Madame", "Madam / Mrs."),
    ("Mademoiselle", "Miss"),
    ("Gens", "People"),
    ("Personne", "Person / Nobody"),
    ("Étranger", "Foreigner / Stranger"),
    ("Inconnu", "Unknown person"),
    ("Vieillard", "Old man"),
    ("Vieille", "Old woman"),
    ("Adolescent", "Teenager (m)"),
    ("Adolescente", "Teenager (f)"),
    ("Adulte", "Adult"),
    ("Jeune", "Young person"),
    ("Vieux", "Old person"),
    ("Jumeau", "Twin (m)"),
    ("Jumelle", "Twin (f)"),
    ("Orphelin", "Orphan (m)"),
    ("Veuve", "Widow"),
    ("Veuf", "Widower"),
    ("Docteur", "Doctor"),
    ("Médecin", "Physician"),
    ("Infirmier", "Nurse (m)"),
    ("Infirmière", "Nurse (f)"),
    ("Dentiste", "Dentist"),
    ("Pharmacien", "Pharmacist"),
    ("Chirurgien", "Surgeon"),
    ("Vétérinaire", "Veterinarian"),
    ("Professeur", "Teacher / Professor"),
    ("Instituteur", "Primary teacher"),
    ("Étudiant", "Student (m)"),
    ("Étudiante", "Student (f)"),
    ("Élève", "Pupil"),
    ("Directeur", "Director"),
    ("Ingénieur", "Engineer"),
    ("Architecte", "Architect"),
    ("Avocat", "Lawyer"),
    ("Juge", "Judge"),
    ("Notaire", "Notary"),
    ("Policier", "Police officer"),
    ("Gendarme", "Police officer"),
    ("Pompier", "Firefighter"),
    ("Soldat", "Soldier"),
    ("Général", "General"),
    ("Capitaine", "Captain"),
    ("Cuisinier", "Cook / Chef"),
    ("Boulanger", "Baker"),
    ("Boucher", "Butcher"),
    ("Pâtissier", "Pastry chef"),
    ("Serveur", "Waiter"),
    ("Serveuse", "Waitress"),
    ("Barman", "Bartender"),
    ("Artiste", "Artist"),
    ("Peintre", "Painter"),
    ("Sculpteur", "Sculptor"),
    ("Écrivain", "Writer"),
    ("Auteur", "Author"),
    ("Journaliste", "Journalist"),
    ("Musicien", "Musician"),
    ("Chanteur", "Singer (m)"),
    ("Chanteuse", "Singer (f)"),
    ("Compositeur", "Composer"),
    ("Acteur", "Actor (m)"),
    ("Actrice", "Actress"),
    ("Danseur", "Dancer (m)"),
    ("Danseuse", "Dancer (f)"),
    ("Photographe", "Photographer"),
    ("Réalisateur", "Director"),
    ("Pilote", "Pilot"),
    ("Steward", "Flight attendant"),
    ("Chauffeur", "Driver"),
    ("Facteur", "Postman"),
    ("Coiffeur", "Hairdresser (m)"),
    ("Coiffeuse", "Hairdresser (f)"),
    ("Vendeur", "Salesperson (m)"),
    ("Vendeuse", "Salesperson (f)"),
    ("Caissier", "Cashier (m)"),
    ("Caissière", "Cashier (f)"),
    ("Fermier", "Farmer"),
    ("Pêcheur", "Fisherman"),
    ("Jardinier", "Gardener"),
    ("Menuisier", "Carpenter"),
    ("Plombier", "Plumber"),
    ("Électricien", "Electrician"),
    ("Mécanicien", "Mechanic"),
    ("Maçon", "Mason"),
    ("Peintre en bâtiment", "House painter"),
    ("Banquier", "Banker"),
    ("Comptable", "Accountant"),
    ("Secrétaire", "Secretary"),
    ("Assistant", "Assistant"),
    ("Prêtre", "Priest"),
    ("Pasteur", "Pastor"),
    ("Rabbin", "Rabbi"),
    ("Imam", "Imam"),

    # ===== FOOD & DRINK (451-650) =====
    ("Nourriture", "Food"),
    ("Aliment", "Food item"),
    ("Repas", "Meal"),
    ("Petit déjeuner", "Breakfast"),
    ("Déjeuner", "Lunch"),
    ("Dîner", "Dinner"),
    ("Goûter", "Snack"),
    ("Pain", "Bread"),
    ("Baguette", "Baguette"),
    ("Croissant", "Croissant"),
    ("Pain au chocolat", "Chocolate croissant"),
    ("Brioche", "Brioche"),
    ("Fromage", "Cheese"),
    ("Camembert", "Camembert"),
    ("Brie", "Brie"),
    ("Beurre", "Butter"),
    ("Lait", "Milk"),
    ("Crème", "Cream"),
    ("Yaourt", "Yogurt"),
    ("Œuf", "Egg"),
    ("Omelette", "Omelette"),
    ("Viande", "Meat"),
    ("Poulet", "Chicken"),
    ("Bœuf", "Beef"),
    ("Porc", "Pork"),
    ("Agneau", "Lamb"),
    ("Veau", "Veal"),
    ("Jambon", "Ham"),
    ("Saucisse", "Sausage"),
    ("Steak", "Steak"),
    ("Poisson", "Fish"),
    ("Saumon", "Salmon"),
    ("Thon", "Tuna"),
    ("Crevette", "Shrimp"),
    ("Homard", "Lobster"),
    ("Crabe", "Crab"),
    ("Huître", "Oyster"),
    ("Moule", "Mussel"),
    ("Légume", "Vegetable"),
    ("Fruit", "Fruit"),
    ("Pomme", "Apple"),
    ("Poire", "Pear"),
    ("Banane", "Banana"),
    ("Orange", "Orange"),
    ("Citron", "Lemon"),
    ("Fraise", "Strawberry"),
    ("Cerise", "Cherry"),
    ("Raisin", "Grape"),
    ("Pêche", "Peach"),
    ("Abricot", "Apricot"),
    ("Ananas", "Pineapple"),
    ("Mangue", "Mango"),
    ("Pastèque", "Watermelon"),
    ("Melon", "Melon"),
    ("Kiwi", "Kiwi"),
    ("Framboise", "Raspberry"),
    ("Myrtille", "Blueberry"),
    ("Mûre", "Blackberry"),
    ("Figue", "Fig"),
    ("Datte", "Date"),
    ("Noix", "Walnut"),
    ("Noisette", "Hazelnut"),
    ("Amande", "Almond"),
    ("Cacahuète", "Peanut"),
    ("Noix de coco", "Coconut"),
    ("Tomate", "Tomato"),
    ("Pomme de terre", "Potato"),
    ("Carotte", "Carrot"),
    ("Oignon", "Onion"),
    ("Ail", "Garlic"),
    ("Échalote", "Shallot"),
    ("Salade", "Salad / Lettuce"),
    ("Épinard", "Spinach"),
    ("Chou", "Cabbage"),
    ("Chou-fleur", "Cauliflower"),
    ("Brocoli", "Broccoli"),
    ("Concombre", "Cucumber"),
    ("Courgette", "Zucchini"),
    ("Aubergine", "Eggplant"),
    ("Poivron", "Bell pepper"),
    ("Piment", "Chili pepper"),
    ("Champignon", "Mushroom"),
    ("Haricot", "Bean"),
    ("Petit pois", "Pea"),
    ("Lentille", "Lentil"),
    ("Riz", "Rice"),
    ("Pâtes", "Pasta"),
    ("Spaghetti", "Spaghetti"),
    ("Macaroni", "Macaroni"),
    ("Nouille", "Noodle"),
    ("Semoule", "Semolina"),
    ("Farine", "Flour"),
    ("Sucre", "Sugar"),
    ("Sel", "Salt"),
    ("Poivre", "Pepper"),
    ("Épice", "Spice"),
    ("Huile", "Oil"),
    ("Vinaigre", "Vinegar"),
    ("Sauce", "Sauce"),
    ("Ketchup", "Ketchup"),
    ("Moutarde", "Mustard"),
    ("Mayonnaise", "Mayonnaise"),
    ("Miel", "Honey"),
    ("Confiture", "Jam"),
    ("Chocolat", "Chocolate"),
    ("Bonbon", "Candy"),
    ("Sucre", "Sugar"),
    ("Gâteau", "Cake"),
    ("Tarte", "Pie"),
    ("Biscuit", "Cookie"),
    ("Pain d'épice", "Gingerbread"),
    ("Crêpe", "Crepe"),
    ("Gaufre", "Waffle"),
    ("Beignet", "Donut"),
    ("Glace", "Ice cream"),
    ("Sorbet", "Sorbet"),
    ("Crème brûlée", "Crème brûlée"),
    ("Mousse au chocolat", "Chocolate mousse"),
    ("Café", "Coffee"),
    ("Thé", "Tea"),
    ("Chocolat chaud", "Hot chocolate"),
    ("Jus", "Juice"),
    ("Jus d'orange", "Orange juice"),
    ("Eau", "Water"),
    ("Eau minérale", "Mineral water"),
    ("Soda", "Soda"),
    ("Limonade", "Lemonade"),
    ("Vin", "Wine"),
    ("Vin rouge", "Red wine"),
    ("Vin blanc", "White wine"),
    ("Bière", "Beer"),
    ("Champagne", "Champagne"),
    ("Cidre", "Cider"),
    ("Whisky", "Whisky"),
    ("Vodka", "Vodka"),
    ("Cocktail", "Cocktail"),
    ("Boisson", "Drink / Beverage"),
    ("Verre", "Glass"),
    ("Tasse", "Cup"),
    ("Mug", "Mug"),
    ("Assiette", "Plate"),
    ("Bol", "Bowl"),
    ("Fourchette", "Fork"),
    ("Cuillère", "Spoon"),
    ("Couteau", "Knife"),
    ("Serviette", "Napkin / Towel"),
    ("Nappe", "Tablecloth"),
    ("Bouteille", "Bottle"),
    ("Casserole", "Pan"),
    ("Poêle", "Frying pan"),
    ("Four", "Oven"),
    ("Micro-ondes", "Microwave"),
    ("Réfrigérateur", "Refrigerator"),
    ("Frigo", "Fridge"),
    ("Congélateur", "Freezer"),
    ("Lave-vaisselle", "Dishwasher"),
    ("Restaurant", "Restaurant"),
    ("Café", "Cafe"),
    ("Bistro", "Bistro"),
    ("Brasserie", "Brewery"),
    ("Menu", "Menu"),
    ("Carte", "Menu / Card"),
    ("Addition", "Bill"),
    ("Pourboire", "Tip"),
    ("Recette", "Recipe"),
    ("Cuisine", "Cooking / Kitchen"),
    ("Cuisinier", "Cook"),
    ("Chef", "Chef"),
    ("Gourmet", "Gourmet"),
    ("Gourmand", "Glutton"),
    ("Délicieux", "Delicious"),
    ("Savoureux", "Tasty"),
    ("Sucré", "Sweet"),
    ("Salé", "Salty"),
    ("Amer", "Bitter"),
    ("Acide", "Sour"),
    ("Épicé", "Spicy"),
    ("Fade", "Bland"),
    ("Cru", "Raw"),
    ("Cuit", "Cooked"),
    ("Grillé", "Grilled"),
    ("Rôti", "Roasted"),
    ("Frit", "Fried"),
    ("Bouilli", "Boiled"),
    ("Fumé", "Smoked"),
    ("Frais", "Fresh"),
    ("Pourri", "Rotten"),
    ("Mûr", "Ripe"),

    # ===== ANIMALS (651-800) =====
    ("Animal", "Animal"),
    ("Animal de compagnie", "Pet"),
    ("Chien", "Dog"),
    ("Chiot", "Puppy"),
    ("Chat", "Cat"),
    ("Chaton", "Kitten"),
    ("Cheval", "Horse"),
    ("Jument", "Mare"),
    ("Poulain", "Foal"),
    ("Âne", "Donkey"),
    ("Mule", "Mule"),
    ("Vache", "Cow"),
    ("Taureau", "Bull"),
    ("Veau", "Calf"),
    ("Mouton", "Sheep"),
    ("Bélier", "Ram"),
    ("Agneau", "Lamb"),
    ("Chèvre", "Goat"),
    ("Bouc", "Billy goat"),
    ("Chevreau", "Kid"),
    ("Cochon", "Pig"),
    ("Porc", "Pork / Pig"),
    ("Sanglier", "Wild boar"),
    ("Poule", "Hen"),
    ("Coq", "Rooster"),
    ("Poussin", "Chick"),
    ("Canard", "Duck"),
    ("Oie", "Goose"),
    ("Dinde", "Turkey"),
    ("Pigeon", "Pigeon"),
    ("Tourterelle", "Turtle dove"),
    ("Oiseau", "Bird"),
    ("Aigle", "Eagle"),
    ("Faucon", "Falcon"),
    ("Hibou", "Owl"),
    ("Chouette", "Owl"),
    ("Corbeau", "Crow"),
    ("Corneille", "Crow"),
    ("Pie", "Magpie"),
    ("Moineau", "Sparrow"),
    ("Rouge-gorge", "Robin"),
    ("Hirondelle", "Swallow"),
    ("Perroquet", "Parrot"),
    ("Perruche", "Parakeet"),
    ("Canari", "Canary"),
    ("Papillon", "Butterfly"),
    ("Chenille", "Caterpillar"),
    ("Abeille", "Bee"),
    ("Guêpe", "Wasp"),
    ("Fourmi", "Ant"),
    ("Mouche", "Fly"),
    ("Moustique", "Mosquito"),
    ("Araignée", "Spider"),
    ("Scorpion", "Scorpion"),
    ("Serpent", "Snake"),
    ("Couleuvre", "Grass snake"),
    ("Vipère", "Viper"),
    ("Lézard", "Lizard"),
    ("Gecko", "Gecko"),
    ("Caméléon", "Chameleon"),
    ("Tortue", "Turtle"),
    ("Grenouille", "Frog"),
    ("Crapaud", "Toad"),
    ("Salamandre", "Salamander"),
    ("Lapin", "Rabbit"),
    ("Lièvre", "Hare"),
    ("Écureuil", "Squirrel"),
    ("Souris", "Mouse"),
    ("Rat", "Rat"),
    ("Hamster", "Hamster"),
    ("Cobaye", "Guinea pig"),
    ("Hérisson", "Hedgehog"),
    ("Taupe", "Mole"),
    ("Chauve-souris", "Bat"),
    ("Renard", "Fox"),
    ("Loup", "Wolf"),
    ("Ours", "Bear"),
    ("Ours polaire", "Polar bear"),
    ("Lion", "Lion"),
    ("Lionne", "Lioness"),
    ("Tigre", "Tiger"),
    ("Léopard", "Leopard"),
    ("Panthère", "Panther"),
    ("Guépard", "Cheetah"),
    ("Éléphant", "Elephant"),
    ("Rhinocéros", "Rhinoceros"),
    ("Hippopotame", "Hippopotamus"),
    ("Girafe", "Giraffe"),
    ("Zèbre", "Zebra"),
    ("Singe", "Monkey"),
    ("Chimpanzé", "Chimpanzee"),
    ("Gorille", "Gorilla"),
    ("Orang-outan", "Orangutan"),
    ("Kangourou", "Kangaroo"),
    ("Koala", "Koala"),
    ("Panda", "Panda"),
    ("Lama", "Llama"),
    ("Chameau", "Camel"),
    ("Dromadaire", "Dromedary"),
    ("Bison", "Bison"),
    ("Buffle", "Buffalo"),
    ("Cerf", "Deer"),
    ("Biche", "Doe"),
    ("Chevreuil", "Roe deer"),
    ("Élan", "Moose"),
    ("Renne", "Reindeer"),
    ("Antilope", "Antelope"),
    ("Gazelle", "Gazelle"),
    ("Dauphin", "Dolphin"),
    ("Baleine", "Whale"),
    ("Requin", "Shark"),
    ("Phoque", "Seal"),
    ("Pingouin", "Penguin"),
    ("Morse", "Walrus"),
    ("Pieuvre", "Octopus"),
    ("Calmar", "Squid"),
    ("Méduse", "Jellyfish"),
    ("Étoile de mer", "Starfish"),
    ("Crabe", "Crab"),
    ("Homard", "Lobster"),
    ("Crevette", "Shrimp"),
    ("Coquille", "Shell"),
    ("Escargot", "Snail"),
    ("Ver", "Worm"),
    ("Insecte", "Insect"),
    ("Puce", "Flea"),
    ("Pou", "Louse"),
    ("Cafard", "Cockroach"),
    ("Libellule", "Dragonfly"),
    ("Sauterelle", "Grasshopper"),
    ("Criquet", "Locust"),
    ("Grillon", "Cricket"),
    ("Cigale", "Cicada"),
    ("Luciole", "Firefly"),
    ("Coccinelle", "Ladybug"),
    ("Fourmi", "Ant"),

    # ===== NATURE & WEATHER (801-950) =====
    ("Nature", "Nature"),
    ("Arbre", "Tree"),
    ("Chêne", "Oak"),
    ("Pin", "Pine"),
    ("Sapin", "Fir"),
    ("Bouleau", "Birch"),
    ("Hêtre", "Beech"),
    ("Saule", "Willow"),
    ("Peuplier", "Poplar"),
    ("Érable", "Maple"),
    ("Palmier", "Palm tree"),
    ("Olivier", "Olive tree"),
    ("Pommier", "Apple tree"),
    ("Cerisier", "Cherry tree"),
    ("Rosier", "Rose bush"),
    ("Fleur", "Flower"),
    ("Rose", "Rose"),
    ("Tulipe", "Tulip"),
    ("Marguerite", "Daisy"),
    ("Tournesol", "Sunflower"),
    ("Lys", "Lily"),
    ("Iris", "Iris"),
    ("Pivoine", "Peony"),
    ("Jasmin", "Jasmine"),
    ("Lavande", "Lavender"),
    ("Herbe", "Grass"),
    ("Feuille", "Leaf"),
    ("Racine", "Root"),
    ("Branche", "Branch"),
    ("Tronc", "Trunk"),
    ("Graine", "Seed"),
    ("Fruit", "Fruit"),
    ("Forêt", "Forest"),
    ("Bois", "Wood"),
    ("Jardin", "Garden"),
    ("Champ", "Field"),
    ("Prairie", "Meadow"),
    ("Pré", "Meadow"),
    ("Montagne", "Mountain"),
    ("Colline", "Hill"),
    ("Vallée", "Valley"),
    ("Volcan", "Volcano"),
    ("Glacier", "Glacier"),
    ("Falaise", "Cliff"),
    ("Grotte", "Cave"),
    ("Rivière", "River"),
    ("Fleuve", "Large river"),
    ("Ruisseau", "Stream"),
    ("Cascade", "Waterfall"),
    ("Lac", "Lake"),
    ("Étang", "Pond"),
    ("Marais", "Swamp"),
    ("Mer", "Sea"),
    ("Océan", "Ocean"),
    ("Plage", "Beach"),
    ("Côte", "Coast"),
    ("Île", "Island"),
    ("Presqu'île", "Peninsula"),
    ("Golfe", "Gulf"),
    ("Baie", "Bay"),
    ("Port", "Harbor"),
    ("Désert", "Desert"),
    ("Oasis", "Oasis"),
    ("Plaine", "Plain"),
    ("Plateau", "Plateau"),
    ("Terre", "Earth / Land"),
    ("Sol", "Soil"),
    ("Sable", "Sand"),
    ("Pierre", "Stone"),
    ("Roche", "Rock"),
    ("Caillou", "Pebble"),
    ("Boue", "Mud"),
    ("Poussière", "Dust"),
    ("Ciel", "Sky"),
    ("Soleil", "Sun"),
    ("Lune", "Moon"),
    ("Étoile", "Star"),
    ("Planète", "Planet"),
    ("Univers", "Universe"),
    ("Galaxie", "Galaxy"),
    ("Comète", "Comet"),
    ("Nuage", "Cloud"),
    ("Pluie", "Rain"),
    ("Neige", "Snow"),
    ("Vent", "Wind"),
    ("Orage", "Storm"),
    ("Tempête", "Tempest"),
    ("Tonnerre", "Thunder"),
    ("Éclair", "Lightning"),
    ("Brouillard", "Fog"),
    ("Brume", "Mist"),
    ("Rosée", "Dew"),
    ("Gel", "Frost"),
    ("Glace", "Ice"),
    ("Grêle", "Hail"),
    ("Arc-en-ciel", "Rainbow"),
    ("Feu", "Fire"),
    ("Flamme", "Flame"),
    ("Fumée", "Smoke"),
    ("Cendre", "Ash"),
    ("Air", "Air"),
    ("Oxygène", "Oxygen"),
    ("Saison", "Season"),
    ("Printemps", "Spring"),
    ("Été", "Summer"),
    ("Automne", "Autumn"),
    ("Hiver", "Winter"),
    ("Climat", "Climate"),
    ("Temps", "Weather / Time"),
    ("Chaleur", "Heat"),
    ("Froid", "Cold"),
    ("Fraîcheur", "Coolness"),
    ("Humidité", "Humidity"),
    ("Sécheresse", "Drought"),
    ("Inondation", "Flood"),
    ("Séisme", "Earthquake"),
    ("Éruption", "Eruption"),
    ("Catastrophe", "Disaster"),
    ("Environnement", "Environment"),
    ("Pollution", "Pollution"),
    ("Écologie", "Ecology"),
    ("Recyclage", "Recycling"),
    ("Déchets", "Waste"),
    ("Énergie", "Energy"),
    ("Soleil levant", "Sunrise"),
    ("Coucher de soleil", "Sunset"),
    ("Aube", "Dawn"),
    ("Crépuscule", "Dusk"),
    ("Midi", "Noon"),
    ("Minuit", "Midnight"),

    # ===== BODY & HEALTH (951-1080) =====
    ("Corps", "Body"),
    ("Tête", "Head"),
    ("Visage", "Face"),
    ("Front", "Forehead"),
    ("Œil", "Eye"),
    ("Yeux", "Eyes"),
    ("Sourcil", "Eyebrow"),
    ("Cil", "Eyelash"),
    ("Nez", "Nose"),
    ("Bouche", "Mouth"),
    ("Lèvre", "Lip"),
    ("Dent", "Tooth"),
    ("Langue", "Tongue"),
    ("Gorge", "Throat"),
    ("Oreille", "Ear"),
    ("Cou", "Neck"),
    ("Nuque", "Nape"),
    ("Épaule", "Shoulder"),
    ("Bras", "Arm"),
    ("Coude", "Elbow"),
    ("Poignet", "Wrist"),
    ("Main", "Hand"),
    ("Paume", "Palm"),
    ("Doigt", "Finger"),
    ("Pouce", "Thumb"),
    ("Ongle", "Nail"),
    ("Poitrine", "Chest"),
    ("Sein", "Breast"),
    ("Ventre", "Belly"),
    ("Nombril", "Navel"),
    ("Dos", "Back"),
    ("Rein", "Kidney"),
    ("Fesse", "Buttock"),
    ("Jambe", "Leg"),
    ("Cuisse", "Thigh"),
    ("Genou", "Knee"),
    ("Mollet", "Calf"),
    ("Cheville", "Ankle"),
    ("Pied", "Foot"),
    ("Orteil", "Toe"),
    ("Talon", "Heel"),
    ("Peau", "Skin"),
    ("Cheveu", "Hair (single)"),
    ("Cheveux", "Hair"),
    ("Barbe", "Beard"),
    ("Moustache", "Mustache"),
    ("Sourcils", "Eyebrows"),
    ("Sang", "Blood"),
    ("Veine", "Vein"),
    ("Artère", "Artery"),
    ("Cœur", "Heart"),
    ("Poumon", "Lung"),
    ("Foie", "Liver"),
    ("Estomac", "Stomach"),
    ("Intestin", "Intestine"),
    ("Cerveau", "Brain"),
    ("Os", "Bone"),
    ("Muscle", "Muscle"),
    ("Nerf", "Nerve"),
    ("Santé", "Health"),
    ("Maladie", "Illness"),
    ("Fièvre", "Fever"),
    ("Rhume", "Cold"),
    ("Grippe", "Flu"),
    ("Toux", "Cough"),
    ("Éternuement", "Sneeze"),
    ("Mal de tête", "Headache"),
    ("Mal de ventre", "Stomachache"),
    ("Mal de gorge", "Sore throat"),
    ("Douleur", "Pain"),
    ("Blessure", "Wound"),
    ("Brûlure", "Burn"),
    ("Fracture", "Fracture"),
    ("Entorse", "Sprain"),
    ("Piqûre", "Sting"),
    ("Morsure", "Bite"),
    ("Cicatrice", "Scar"),
    ("Bleu", "Bruise"),
    ("Médicament", "Medicine"),
    ("Comprimé", "Pill"),
    ("Sirop", "Syrup"),
    ("Pommade", "Ointment"),
    ("Pansement", "Bandage"),
    ("Vaccin", "Vaccine"),
    ("Injection", "Injection"),
    ("Ordonnance", "Prescription"),
    ("Docteur", "Doctor"),
    ("Médecin", "Physician"),
    ("Hôpital", "Hospital"),
    ("Clinique", "Clinic"),
    ("Pharmacie", "Pharmacy"),
    ("Urgence", "Emergency"),
    ("Ambulance", "Ambulance"),
    ("Opération", "Operation"),
    ("Chirurgie", "Surgery"),
    ("Repos", "Rest"),
    ("Sommeil", "Sleep"),
    ("Rêve", "Dream"),
    ("Cauchemar", "Nightmare"),
    ("Insomnie", "Insomnia"),
    ("Fatigue", "Fatigue"),
    ("Énergie", "Energy"),
    ("Forme", "Fitness"),
    ("Sport", "Sport"),
    ("Exercice", "Exercise"),
    ("Gymnastique", "Gymnastics"),
    ("Yoga", "Yoga"),
    ("Massage", "Massage"),
    ("Relaxation", "Relaxation"),
    ("Stress", "Stress"),
    ("Anxiété", "Anxiety"),
    ("Dépression", "Depression"),
    ("Bonheur", "Happiness"),
    ("Tristesse", "Sadness"),
    ("Joie", "Joy"),
    ("Peur", "Fear"),
    ("Colère", "Anger"),
    ("Surprise", "Surprise"),
    ("Dégoût", "Disgust"),
    ("Honte", "Shame"),
    ("Fierté", "Pride"),
    ("Jalousie", "Jealousy"),
    ("Envie", "Envy"),
    ("Amour", "Love"),
    ("Haine", "Hatred"),
    ("Amitié", "Friendship"),
    ("Confiance", "Trust"),
    ("Respect", "Respect"),
    ("Courage", "Courage"),
    ("Lâcheté", "Cowardice"),

    # ===== HOUSE & OBJECTS (1081-1250) =====
    ("Maison", "House"),
    ("Appartement", "Apartment"),
    ("Studio", "Studio"),
    ("Villa", "Villa"),
    ("Château", "Castle"),
    ("Cabane", "Cabin"),
    ("Ferme", "Farm"),
    ("Immeuble", "Building"),
    ("Étage", "Floor / Story"),
    ("Rez-de-chaussée", "Ground floor"),
    ("Ascenseur", "Elevator"),
    ("Escalier", "Stairs"),
    ("Palier", "Landing"),
    ("Couloir", "Hallway"),
    ("Entrée", "Entrance"),
    ("Salon", "Living room"),
    ("Salle à manger", "Dining room"),
    ("Cuisine", "Kitchen"),
    ("Chambre", "Bedroom"),
    ("Salle de bain", "Bathroom"),
    ("Toilettes", "Toilet"),
    ("WC", "WC"),
    ("Buanderie", "Laundry room"),
    ("Garage", "Garage"),
    ("Cave", "Cellar"),
    ("Grenier", "Attic"),
    ("Balcon", "Balcony"),
    ("Terrasse", "Terrace"),
    ("Jardin", "Garden"),
    ("Cour", "Yard"),
    ("Portail", "Gate"),
    ("Porte", "Door"),
    ("Poignée", "Handle"),
    ("Serrure", "Lock"),
    ("Clé", "Key"),
    ("Fenêtre", "Window"),
    ("Volet", "Shutter"),
    ("Rideau", "Curtain"),
    ("Store", "Blind"),
    ("Mur", "Wall"),
    ("Sol", "Floor"),
    ("Plafond", "Ceiling"),
    ("Toit", "Roof"),
    ("Cheminée", "Chimney / Fireplace"),
    ("Meuble", "Furniture"),
    ("Table", "Table"),
    ("Chaise", "Chair"),
    ("Tabouret", "Stool"),
    ("Banc", "Bench"),
    ("Lit", "Bed"),
    ("Matelas", "Mattress"),
    ("Oreiller", "Pillow"),
    ("Couverture", "Blanket"),
    ("Drap", "Sheet"),
    ("Canapé", "Sofa"),
    ("Fauteuil", "Armchair"),
    ("Divan", "Divan"),
    ("Armoire", "Wardrobe"),
    ("Commode", "Dresser"),
    ("Étagère", "Shelf"),
    ("Bibliothèque", "Bookcase / Library"),
    ("Bureau", "Desk / Office"),
    ("Tiroir", "Drawer"),
    ("Placard", "Closet"),
    ("Coffre", "Chest"),
    ("Lampe", "Lamp"),
    ("Lustre", "Chandelier"),
    ("Bougie", "Candle"),
    ("Lampe de poche", "Flashlight"),
    ("Miroir", "Mirror"),
    ("Tapis", "Carpet"),
    ("Moquette", "Carpet"),
    ("Carrelage", "Tiling"),
    ("Peinture", "Painting"),
    ("Papier peint", "Wallpaper"),
    ("Cadre", "Frame"),
    ("Affiche", "Poster"),
    ("Photo", "Photo"),
    ("Horloge", "Clock"),
    ("Réveil", "Alarm clock"),
    ("Montre", "Watch"),
    ("Calendrier", "Calendar"),
    ("Agenda", "Planner"),
    ("Stylo", "Pen"),
    ("Crayon", "Pencil"),
    ("Gomme", "Eraser"),
    ("Règle", "Ruler"),
    ("Ciseaux", "Scissors"),
    ("Colle", "Glue"),
    ("Papier", "Paper"),
    ("Cahier", "Notebook"),
    ("Livre", "Book"),
    ("Journal", "Newspaper"),
    ("Magazine", "Magazine"),
    ("Carte", "Card / Map"),
    ("Enveloppe", "Envelope"),
    ("Timbre", "Stamp"),
    ("Lettre", "Letter"),
    ("Colis", "Parcel"),
    ("Sac", "Bag"),
    ("Sac à dos", "Backpack"),
    ("Valise", "Suitcase"),
    ("Portefeuille", "Wallet"),
    ("Porte-monnaie", "Coin purse"),
    ("Bijou", "Jewel"),
    ("Bague", "Ring"),
    ("Collier", "Necklace"),
    ("Bracelet", "Bracelet"),
    ("Boucle d'oreille", "Earring"),
    ("Broche", "Brooch"),
    ("Lunettes", "Glasses"),
    ("Lunettes de soleil", "Sunglasses"),
    ("Chapeau", "Hat"),
    ("Casquette", "Cap"),
    ("Béret", "Beret"),
    ("Écharpe", "Scarf"),
    ("Foulard", "Scarf"),
    ("Gant", "Glove"),
    ("Ceinture", "Belt"),
    ("Cravate", "Tie"),
    ("Nœud papillon", "Bow tie"),
    ("Chaussure", "Shoe"),
    ("Botte", "Boot"),
    ("Sandale", "Sandal"),
    ("Pantoufle", "Slipper"),
    ("Chaussette", "Sock"),
    ("Collant", "Tights"),
    ("Chemise", "Shirt"),
    ("T-shirt", "T-shirt"),
    ("Polo", "Polo shirt"),
    ("Pull", "Sweater"),
    ("Gilet", "Cardigan"),
    ("Veste", "Jacket"),
    ("Manteau", "Coat"),
    ("Imperméable", "Raincoat"),
    ("Pantalon", "Pants"),
    ("Jean", "Jeans"),
    ("Short", "Shorts"),
    ("Jupe", "Skirt"),
    ("Robe", "Dress"),
    ("Costume", "Suit"),
    ("Tablier", "Apron"),
    ("Pyjama", "Pajamas"),
    ("Maillot de bain", "Swimsuit"),
    ("Serviette", "Towel"),
    ("Savon", "Soap"),
    ("Shampooing", "Shampoo"),
    ("Gel douche", "Shower gel"),
    ("Dentifrice", "Toothpaste"),
    ("Brosse à dents", "Toothbrush"),
    ("Peigne", "Comb"),
    ("Brosse", "Brush"),
    ("Sèche-cheveux", "Hair dryer"),
    ("Rasoir", "Razor"),
    ("Parfum", "Perfume"),
    ("Crème", "Cream"),
    ("Maquillage", "Makeup"),
    ("Rouge à lèvres", "Lipstick"),
    ("Papier toilette", "Toilet paper"),
    ("Mouchoir", "Tissue"),

    # ===== PLACES & TRAVEL (1251-1420) =====
    ("Ville", "City"),
    ("Village", "Village"),
    ("Bourg", "Small town"),
    ("Métropole", "Metropolis"),
    ("Capitale", "Capital"),
    ("Quartier", "Neighborhood"),
    ("Banlieue", "Suburb"),
    ("Centre-ville", "City center"),
    ("Rue", "Street"),
    ("Avenue", "Avenue"),
    ("Boulevard", "Boulevard"),
    ("Place", "Square"),
    ("Ruelle", "Alley"),
    ("Impasse", "Dead end"),
    ("Route", "Road"),
    ("Chemin", "Path"),
    ("Autoroute", "Highway"),
    ("Pont", "Bridge"),
    ("Tunnel", "Tunnel"),
    ("Carrefour", "Intersection"),
    ("Rond-point", "Roundabout"),
    ("Feu rouge", "Traffic light"),
    ("Panneau", "Sign"),
    ("Trottoir", "Sidewalk"),
    ("Passage piéton", "Crosswalk"),
    ("Pays", "Country"),
    ("Région", "Region"),
    ("Province", "Province"),
    ("Département", "Department"),
    ("Frontière", "Border"),
    ("Douane", "Customs"),
    ("Préfecture", "Prefecture"),
    ("Mairie", "Town hall"),
    ("Tribunal", "Court"),
    ("Prison", "Prison"),
    ("Commissariat", "Police station"),
    ("Caserne", "Barracks"),
    ("Ambassade", "Embassy"),
    ("Consulat", "Consulate"),
    ("Magasin", "Shop"),
    ("Boutique", "Boutique"),
    ("Marché", "Market"),
    ("Supermarché", "Supermarket"),
    ("Hypermarché", "Hypermarket"),
    ("Épicerie", "Grocery"),
    ("Boulangerie", "Bakery"),
    ("Boucherie", "Butcher shop"),
    ("Poissonnerie", "Fish shop"),
    ("Pâtisserie", "Pastry shop"),
    ("Charcuterie", "Deli"),
    ("Fromagerie", "Cheese shop"),
    ("Pharmacie", "Pharmacy"),
    ("Librairie", "Bookstore"),
    ("Papeterie", "Stationery shop"),
    ("Fleuriste", "Florist"),
    ("Coiffeur", "Hairdresser"),
    ("Cordonnerie", "Cobbler"),
    ("Laverie", "Laundry"),
    ("Pressing", "Dry cleaner"),
    ("Banque", "Bank"),
    ("Bureau de poste", "Post office"),
    ("Hôpital", "Hospital"),
    ("Clinique", "Clinic"),
    ("École", "School"),
    ("Collège", "Middle school"),
    ("Lycée", "High school"),
    ("Université", "University"),
    ("Bibliothèque", "Library"),
    ("Musée", "Museum"),
    ("Galerie", "Gallery"),
    ("Théâtre", "Theater"),
    ("Cinéma", "Cinema"),
    ("Opéra", "Opera"),
    ("Salle de concert", "Concert hall"),
    ("Restaurant", "Restaurant"),
    ("Brasserie", "Brewery"),
    ("Café", "Cafe"),
    ("Bar", "Bar"),
    ("Boîte de nuit", "Nightclub"),
    ("Hôtel", "Hotel"),
    ("Auberge", "Inn"),
    ("Camping", "Campsite"),
    ("Gîte", "Cottage"),
    ("Gare", "Train station"),
    ("Aéroport", "Airport"),
    ("Port", "Harbor"),
    ("Station de métro", "Subway station"),
    ("Arrêt de bus", "Bus stop"),
    ("Parking", "Parking lot"),
    ("Station-service", "Gas station"),
    ("Église", "Church"),
    ("Cathédrale", "Cathedral"),
    ("Chapelle", "Chapel"),
    ("Mosquée", "Mosque"),
    ("Synagogue", "Synagogue"),
    ("Temple", "Temple"),
    ("Cimetière", "Cemetery"),
    ("Palais", "Palace"),
    ("Monument", "Monument"),
    ("Statue", "Statue"),
    ("Tour", "Tower"),
    ("Château", "Castle"),
    ("Fort", "Fort"),
    ("Ruines", "Ruins"),
    ("Parc", "Park"),
    ("Square", "Small park"),
    ("Jardin public", "Public garden"),
    ("Zoo", "Zoo"),
    ("Aquarium", "Aquarium"),
    ("Plage", "Beach"),
    ("Piscine", "Pool"),
    ("Stade", "Stadium"),
    ("Gymnase", "Gym"),
    ("Terrain de sport", "Sports field"),
    ("Voyage", "Trip / Journey"),
    ("Vacances", "Vacation"),
    ("Tourisme", "Tourism"),
    ("Touriste", "Tourist"),
    ("Guide", "Guide"),
    ("Carte", "Map / Card"),
    ("Boussole", "Compass"),
    ("Direction", "Direction"),
    ("Nord", "North"),
    ("Sud", "South"),
    ("Est", "East"),
    ("Ouest", "West"),
    ("Gauche", "Left"),
    ("Droite", "Right"),
    ("Tout droit", "Straight ahead"),
    ("Loin", "Far"),
    ("Près", "Near"),
    ("Ici", "Here"),
    ("Là", "There"),
    ("Partout", "Everywhere"),
    ("Nulle part", "Nowhere"),
    ("Quelque part", "Somewhere"),
    ("Bagages", "Luggage"),
    ("Billet", "Ticket"),
    ("Réservation", "Reservation"),
    ("Passeport", "Passport"),
    ("Visa", "Visa"),
    ("Avion", "Airplane"),
    ("Train", "Train"),
    ("Bus", "Bus"),
    ("Car", "Coach"),
    ("Métro", "Subway"),
    ("Tramway", "Tram"),
    ("Taxi", "Taxi"),
    ("Voiture", "Car"),
    ("Vélo", "Bicycle"),
    ("Moto", "Motorcycle"),
    ("Scooter", "Scooter"),
    ("Camion", "Truck"),
    ("Bateau", "Boat"),
    ("Navire", "Ship"),
    ("Ferry", "Ferry"),
    ("Voilier", "Sailboat"),
    ("Essence", "Gasoline"),
    ("Carburant", "Fuel"),
    ("Diesel", "Diesel"),
    ("Pneu", "Tire"),
    ("Roue", "Wheel"),
    ("Volant", "Steering wheel"),
    ("Frein", "Brake"),
    ("Moteur", "Engine"),
    ("Phares", "Headlights"),
    ("Ceinture de sécurité", "Seatbelt"),
    ("Casque", "Helmet"),

    # ===== TIME & NUMBERS (1421-1520) =====
    ("Temps", "Time"),
    ("Heure", "Hour"),
    ("Minute", "Minute"),
    ("Seconde", "Second"),
    ("Matin", "Morning"),
    ("Après-midi", "Afternoon"),
    ("Soir", "Evening"),
    ("Nuit", "Night"),
    ("Aujourd'hui", "Today"),
    ("Hier", "Yesterday"),
    ("Demain", "Tomorrow"),
    ("Après-demain", "Day after tomorrow"),
    ("Avant-hier", "Day before yesterday"),
    ("Maintenant", "Now"),
    ("Bientôt", "Soon"),
    ("Tôt", "Early"),
    ("Tard", "Late"),
    ("Toujours", "Always"),
    ("Jamais", "Never"),
    ("Souvent", "Often"),
    ("Parfois", "Sometimes"),
    ("Rarement", "Rarely"),
    ("Encore", "Again / Still"),
    ("Déjà", "Already"),
    ("Enfin", "Finally"),
    ("Jour", "Day"),
    ("Semaine", "Week"),
    ("Mois", "Month"),
    ("Année", "Year"),
    ("Siècle", "Century"),
    ("Millénaire", "Millennium"),
    ("Lundi", "Monday"),
    ("Mardi", "Tuesday"),
    ("Mercredi", "Wednesday"),
    ("Jeudi", "Thursday"),
    ("Vendredi", "Friday"),
    ("Samedi", "Saturday"),
    ("Dimanche", "Sunday"),
    ("Janvier", "January"),
    ("Février", "February"),
    ("Mars", "March"),
    ("Avril", "April"),
    ("Mai", "May"),
    ("Juin", "June"),
    ("Juillet", "July"),
    ("Août", "August"),
    ("Septembre", "September"),
    ("Octobre", "October"),
    ("Novembre", "November"),
    ("Décembre", "December"),
    ("Un", "One"),
    ("Deux", "Two"),
    ("Trois", "Three"),
    ("Quatre", "Four"),
    ("Cinq", "Five"),
    ("Six", "Six"),
    ("Sept", "Seven"),
    ("Huit", "Eight"),
    ("Neuf", "Nine"),
    ("Dix", "Ten"),
    ("Onze", "Eleven"),
    ("Douze", "Twelve"),
    ("Treize", "Thirteen"),
    ("Quatorze", "Fourteen"),
    ("Quinze", "Fifteen"),
    ("Seize", "Sixteen"),
    ("Dix-sept", "Seventeen"),
    ("Dix-huit", "Eighteen"),
    ("Dix-neuf", "Nineteen"),
    ("Vingt", "Twenty"),
    ("Trente", "Thirty"),
    ("Quarante", "Forty"),
    ("Cinquante", "Fifty"),
    ("Soixante", "Sixty"),
    ("Soixante-dix", "Seventy"),
    ("Quatre-vingts", "Eighty"),
    ("Quatre-vingt-dix", "Ninety"),
    ("Cent", "Hundred"),
    ("Deux cents", "Two hundred"),
    ("Mille", "Thousand"),
    ("Million", "Million"),
    ("Milliard", "Billion"),
    ("Premier", "First"),
    ("Deuxième", "Second"),
    ("Troisième", "Third"),
    ("Quatrième", "Fourth"),
    ("Cinquième", "Fifth"),
    ("Dernier", "Last"),
    ("Prochain", "Next"),
    ("Précédent", "Previous"),
    ("Début", "Beginning"),
    ("Fin", "End"),
    ("Milieu", "Middle"),
    ("Moment", "Moment"),
    ("Instant", "Instant"),
    ("Période", "Period"),
    ("Durée", "Duration"),
    ("Fois", "Time (occurrence)"),
    ("Date", "Date"),
    ("Rendez-vous", "Appointment"),

    # ===== COLORS & ADJECTIVES (1521-1700) =====
    ("Couleur", "Color"),
    ("Rouge", "Red"),
    ("Bleu", "Blue"),
    ("Vert", "Green"),
    ("Jaune", "Yellow"),
    ("Orange", "Orange"),
    ("Violet", "Purple"),
    ("Rose", "Pink"),
    ("Marron", "Brown"),
    ("Noir", "Black"),
    ("Blanc", "White"),
    ("Gris", "Gray"),
    ("Doré", "Golden"),
    ("Argenté", "Silver"),
    ("Beige", "Beige"),
    ("Turquoise", "Turquoise"),
    ("Bordeaux", "Burgundy"),
    ("Grand", "Big / Tall"),
    ("Petit", "Small"),
    ("Gros", "Fat / Big"),
    ("Maigre", "Thin / Skinny"),
    ("Long", "Long"),
    ("Court", "Short"),
    ("Haut", "High / Tall"),
    ("Bas", "Low"),
    ("Large", "Wide"),
    ("Étroit", "Narrow"),
    ("Épais", "Thick"),
    ("Mince", "Slim"),
    ("Lourd", "Heavy"),
    ("Léger", "Light"),
    ("Plein", "Full"),
    ("Vide", "Empty"),
    ("Chaud", "Hot"),
    ("Froid", "Cold"),
    ("Tiède", "Warm"),
    ("Frais", "Fresh / Cool"),
    ("Doux", "Soft / Sweet"),
    ("Dur", "Hard"),
    ("Mou", "Soft"),
    ("Lisse", "Smooth"),
    ("Rugueux", "Rough"),
    ("Pointu", "Sharp"),
    ("Émoussé", "Blunt"),
    ("Vieux", "Old"),
    ("Jeune", "Young"),
    ("Nouveau", "New"),
    ("Ancien", "Ancient"),
    ("Moderne", "Modern"),
    ("Beau", "Beautiful"),
    ("Joli", "Pretty"),
    ("Mignon", "Cute"),
    ("Laid", "Ugly"),
    ("Bon", "Good"),
    ("Mauvais", "Bad"),
    ("Meilleur", "Better"),
    ("Pire", "Worse"),
    ("Excellent", "Excellent"),
    ("Parfait", "Perfect"),
    ("Content", "Happy"),
    ("Heureux", "Happy"),
    ("Malheureux", "Unhappy"),
    ("Triste", "Sad"),
    ("Fatigué", "Tired"),
    ("Reposé", "Rested"),
    ("Malade", "Sick"),
    ("En forme", "Fit"),
    ("Fort", "Strong"),
    ("Faible", "Weak"),
    ("Riche", "Rich"),
    ("Pauvre", "Poor"),
    ("Célèbre", "Famous"),
    ("Inconnu", "Unknown"),
    ("Facile", "Easy"),
    ("Difficile", "Difficult"),
    ("Simple", "Simple"),
    ("Compliqué", "Complicated"),
    ("Propre", "Clean"),
    ("Sale", "Dirty"),
    ("Ouvert", "Open"),
    ("Fermé", "Closed"),
    ("Vrai", "True"),
    ("Faux", "False"),
    ("Même", "Same"),
    ("Différent", "Different"),
    ("Autre", "Other"),
    ("Premier", "First"),
    ("Dernier", "Last"),
    ("Prochain", "Next"),
    ("Prêt", "Ready"),
    ("Occupé", "Busy"),
    ("Libre", "Free"),
    ("Utile", "Useful"),
    ("Inutile", "Useless"),
    ("Important", "Important"),
    ("Nécessaire", "Necessary"),
    ("Possible", "Possible"),
    ("Impossible", "Impossible"),
    ("Certain", "Certain"),
    ("Incertain", "Uncertain"),
    ("Sûr", "Sure"),
    ("Douteux", "Doubtful"),
    ("Clair", "Clear"),
    ("Obscur", "Dark"),
    ("Sombre", "Dark"),
    ("Brillant", "Bright"),
    ("Lumineux", "Luminous"),
    ("Pâle", "Pale"),
    ("Vif", "Bright / Vivid"),
    ("Terne", "Dull"),
    ("Riche", "Rich"),
    ("Délicieux", "Delicious"),
    ("Dégoûtant", "Disgusting"),
    ("Étrange", "Strange"),
    ("Normal", "Normal"),
    ("Bizarre", "Weird"),
    ("Génial", "Great"),
    ("Super", "Super"),
    ("Formidable", "Wonderful"),
    ("Magnifique", "Magnificent"),
    ("Splendide", "Splendid"),
    ("Horrible", "Horrible"),
    ("Terrible", "Terrible"),
    ("Affreux", "Awful"),
    ("Épouvantable", "Appalling"),
    ("Sympathique", "Nice"),
    ("Antipathique", "Unpleasant"),
    ("Gentil", "Kind"),
    ("Méchant", "Mean"),
    ("Poli", "Polite"),
    ("Impolie", "Rude"),
    ("Honnête", "Honest"),
    ("Malhonnête", "Dishonest"),
    ("Intelligent", "Intelligent"),
    ("Bête", "Stupid"),
    ("Malin", "Clever"),
    ("Naïf", "Naive"),
    ("Sage", "Wise"),
    ("Fou", "Crazy"),
    ("Calme", "Calm"),
    ("Agité", "Agitated"),
    ("Timide", "Shy"),
    ("Audacieux", "Bold"),
    ("Généreux", "Generous"),
    ("Avare", "Stingy"),
    ("Patient", "Patient"),
    ("Impatient", "Impatient"),
    ("Curieux", "Curious"),
    ("Indifférent", "Indifferent"),
    ("Optimiste", "Optimistic"),
    ("Pessimiste", "Pessimistic"),

    # ===== ABSTRACT NOUNS (1701-1870) =====
    ("Amour", "Love"),
    ("Amitié", "Friendship"),
    ("Bonheur", "Happiness"),
    ("Tristesse", "Sadness"),
    ("Joie", "Joy"),
    ("Peur", "Fear"),
    ("Colère", "Anger"),
    ("Surprise", "Surprise"),
    ("Espoir", "Hope"),
    ("Rêve", "Dream"),
    ("Pensée", "Thought"),
    ("Idée", "Idea"),
    ("Imagination", "Imagination"),
    ("Mémoire", "Memory"),
    ("Raison", "Reason"),
    ("Vérité", "Truth"),
    ("Mensonge", "Lie"),
    ("Secret", "Secret"),
    ("Silence", "Silence"),
    ("Bruit", "Noise"),
    ("Paix", "Peace"),
    ("Guerre", "War"),
    ("Liberté", "Freedom"),
    ("Justice", "Justice"),
    ("Injustice", "Injustice"),
    ("Droit", "Right / Law"),
    ("Loi", "Law"),
    ("Règle", "Rule"),
    ("Ordre", "Order"),
    ("Désordre", "Disorder"),
    ("Pouvoir", "Power"),
    ("Force", "Strength"),
    ("Faiblesse", "Weakness"),
    ("Courage", "Courage"),
    ("Sagesse", "Wisdom"),
    ("Folie", "Madness"),
    ("Intelligence", "Intelligence"),
    ("Talent", "Talent"),
    ("Travail", "Work"),
    ("Métier", "Job / Trade"),
    ("Carrière", "Career"),
    ("Succès", "Success"),
    ("Échec", "Failure"),
    ("Effort", "Effort"),
    ("Progrès", "Progress"),
    ("Changement", "Change"),
    ("Vie", "Life"),
    ("Mort", "Death"),
    ("Naissance", "Birth"),
    ("Jeunesse", "Youth"),
    ("Vieillesse", "Old age"),
    ("Santé", "Health"),
    ("Maladie", "Illness"),
    ("Beauté", "Beauty"),
    ("Laideur", "Ugliness"),
    ("Art", "Art"),
    ("Culture", "Culture"),
    ("Histoire", "History / Story"),
    ("Géographie", "Geography"),
    ("Science", "Science"),
    ("Mathématiques", "Mathematics"),
    ("Philosophie", "Philosophy"),
    ("Religion", "Religion"),
    ("Politique", "Politics"),
    ("Économie", "Economy"),
    ("Société", "Society"),
    ("Nature", "Nature"),
    ("Environnement", "Environment"),
    ("Monde", "World"),
    ("Univers", "Universe"),
    ("Terre", "Earth"),
    ("Ciel", "Sky / Heaven"),
    ("Enfer", "Hell"),
    ("Paradis", "Paradise"),
    ("Dieu", "God"),
    ("Ange", "Angel"),
    ("Démon", "Demon"),
    ("Esprit", "Spirit / Mind"),
    ("Âme", "Soul"),
    ("Corps", "Body"),
    ("Musique", "Music"),
    ("Chanson", "Song"),
    ("Danse", "Dance"),
    ("Théâtre", "Theater"),
    ("Cinéma", "Cinema"),
    ("Film", "Movie"),
    ("Photo", "Photo"),
    ("Peinture", "Painting"),
    ("Sculpture", "Sculpture"),
    ("Littérature", "Literature"),
    ("Poésie", "Poetry"),
    ("Roman", "Novel"),
    ("Poème", "Poem"),
    ("Conte", "Tale"),
    ("Légende", "Legend"),
    ("Mythe", "Myth"),
    ("Fable", "Fable"),
    ("Histoire vraie", "True story"),
    ("Récit", "Narrative"),
    ("Récit", "Story"),
    ("École", "School"),
    ("Éducation", "Education"),
    ("Enseignement", "Teaching"),
    ("Étude", "Study"),
    ("Cours", "Class"),
    ("Leçon", "Lesson"),
    ("Devoir", "Homework"),
    ("Examen", "Exam"),
    ("Note", "Grade"),
    ("Diplôme", "Diploma"),
    ("Certificat", "Certificate"),
    ("Université", "University"),
    ("Recherche", "Research"),
    ("Découverte", "Discovery"),
    ("Invention", "Invention"),
    ("Technologie", "Technology"),
    ("Informatique", "Computer science"),
    ("Internet", "Internet"),
    ("Réseau", "Network"),
    ("Site", "Website"),
    ("Application", "Application"),
    ("Logiciel", "Software"),
    ("Ordinateur", "Computer"),
    ("Téléphone", "Phone"),
    ("Smartphone", "Smartphone"),
    ("Tablette", "Tablet"),
    ("Écran", "Screen"),
    ("Clavier", "Keyboard"),
    ("Souris", "Mouse"),
    ("Message", "Message"),
    ("Courriel", "Email"),
    ("Lettre", "Letter"),
    ("Appel", "Call"),
    ("Communication", "Communication"),
    ("Information", "Information"),
    ("Nouvelle", "News"),
    ("Journal", "Newspaper"),
    ("Télévision", "Television"),
    ("Radio", "Radio"),

    # ===== COMMON ADVERBS & PREPOSITIONS (1871-1960) =====
    ("Très", "Very"),
    ("Trop", "Too much"),
    ("Assez", "Enough"),
    ("Peu", "Little / Few"),
    ("Beaucoup", "A lot"),
    ("Tant", "So much"),
    ("Autant", "As much"),
    ("Plus", "More"),
    ("Moins", "Less"),
    ("Aussi", "Also / Too"),
    ("Non plus", "Neither"),
    ("Bien", "Well"),
    ("Mal", "Badly"),
    ("Mieux", "Better"),
    ("Pire", "Worse"),
    ("Même", "Even"),
    ("Surtout", "Especially"),
    ("Surtout", "Above all"),
    ("Sauf", "Except"),
    ("Selon", "According to"),
    ("Malgré", "Despite"),
    ("Pendant", "During"),
    ("Depuis", "Since"),
    ("Jusqu'à", "Until"),
    ("Après", "After"),
    ("Avant", "Before"),
    ("Avec", "With"),
    ("Sans", "Without"),
    ("Pour", "For"),
    ("Contre", "Against"),
    ("Sur", "On"),
    ("Sous", "Under"),
    ("Dans", "In"),
    ("Chez", "At (someone's)"),
    ("Vers", "Towards"),
    ("Entre", "Between"),
    ("Parmi", "Among"),
    ("Hors de", "Outside"),
    ("Au-dessus", "Above"),
    ("Au-dessous", "Below"),
    ("Devant", "In front of"),
    ("Derrière", "Behind"),
    ("À côté de", "Next to"),
    ("Loin de", "Far from"),
    ("Près de", "Near"),
    ("Autour de", "Around"),
    ("À travers", "Through"),
    ("Le long de", "Along"),
    ("Au-delà", "Beyond"),
    ("Ici", "Here"),
    ("Là", "There"),
    ("Là-bas", "Over there"),
    ("Partout", "Everywhere"),
    ("Ailleurs", "Elsewhere"),
    ("Dedans", "Inside"),
    ("Dehors", "Outside"),
    ("Dessus", "On top"),
    ("Dessous", "Underneath"),
    ("Oui", "Yes"),
    ("Non", "No"),
    ("Si", "Yes (contradiction)"),
    ("Peut-être", "Maybe"),
    ("Certainement", "Certainly"),
    ("Sûrement", "Surely"),
    ("Probablement", "Probably"),
    ("Rarement", "Rarely"),
    ("Souvent", "Often"),
    ("Parfois", "Sometimes"),
    ("Jamais", "Never"),
    ("Toujours", "Always"),
    ("Déjà", "Already"),
    ("Encore", "Still / Again"),
    ("Enfin", "Finally"),
    ("Alors", "Then / So"),
    ("Donc", "Therefore"),
    ("Ainsi", "Thus"),
    ("Pourtant", "However"),
    ("Cependant", "However"),
    ("Néanmoins", "Nevertheless"),
    ("Par contre", "On the other hand"),
    ("En effet", "Indeed"),
    ("En fait", "In fact"),
    ("Au fait", "By the way"),
    ("D'ailleurs", "Moreover"),
    ("Sinon", "Otherwise"),
    ("Autrement", "Otherwise"),
    ("Ensemble", "Together"),
    ("Séparément", "Separately"),
    ("Seul", "Alone"),
    ("Vite", "Fast"),
    ("Lentement", "Slowly"),
    ("Doucement", "Gently"),
    ("Fortement", "Strongly"),
    ("Facilement", "Easily"),
    ("Difficilement", "With difficulty"),

    # ===== MISC COMMON WORDS (1961-2000+) =====
    ("Chose", "Thing"),
    ("Truc", "Thing (informal)"),
    ("Endroit", "Place"),
    ("Lieu", "Location"),
    ("Exemple", "Example"),
    ("Problème", "Problem"),
    ("Solution", "Solution"),
    ("Question", "Question"),
    ("Réponse", "Answer"),
    ("Sujet", "Subject / Topic"),
    ("Mot", "Word"),
    ("Phrase", "Sentence"),
    ("Paragraphe", "Paragraph"),
    ("Texte", "Text"),
    ("Page", "Page"),
    ("Chapitre", "Chapter"),
    ("Partie", "Part"),
    ("Section", "Section"),
    ("Liste", "List"),
    ("Point", "Point"),
    ("Ligne", "Line"),
    ("Cercle", "Circle"),
    ("Carré", "Square"),
    ("Triangle", "Triangle"),
    ("Rectangle", "Rectangle"),
    ("Forme", "Shape"),
    ("Taille", "Size"),
    ("Poids", "Weight"),
    ("Mesure", "Measurement"),
    ("Nombre", "Number"),
    ("Chiffre", "Digit"),
    ("Quantité", "Quantity"),
    ("Qualité", "Quality"),
    ("Type", "Type"),
    ("Genre", "Kind / Gender"),
    ("Sorte", "Sort"),
    ("Espèce", "Species"),
    ("Catégorie", "Category"),
    ("Classe", "Class"),
    ("Groupe", "Group"),
    ("Équipe", "Team"),
    ("Ensemble", "Set"),
    ("Collection", "Collection"),
    ("Série", "Series"),
    ("Suite", "Continuation"),
    ("Début", "Start"),
    ("Milieu", "Middle"),
    ("Fin", "End"),
    ("Bord", "Edge"),
    ("Coin", "Corner"),
    ("Centre", "Center"),
    ("Côté", "Side"),
    ("Face", "Face / Side"),
    ("Dos", "Back"),
    ("Dessus", "Top"),
    ("Dessous", "Bottom"),
    ("Haut", "Top"),
    ("Bas", "Bottom"),
    ("Intérieur", "Interior"),
    ("Extérieur", "Exterior"),
    ("Ouverture", "Opening"),
    ("Fermeture", "Closing"),
    ("Entrée", "Entry"),
    ("Sortie", "Exit"),
    ("Passage", "Passage"),
    ("Chemin", "Way"),
    ("Moyen", "Means"),
    ("Manière", "Manner"),
    ("Façon", "Way"),
    ("Méthode", "Method"),
    ("Système", "System"),
    ("Processus", "Process"),
    ("Développement", "Development"),
    ("Croissance", "Growth"),
    ("Évolution", "Evolution"),
    ("Transformation", "Transformation"),
    ("Révolution", "Revolution"),
    ("Mouvement", "Movement"),
    ("Action", "Action"),
    ("Réaction", "Reaction"),
    ("Résultat", "Result"),
    ("Conséquence", "Consequence"),
    ("Cause", "Cause"),
    ("Effet", "Effect"),
    ("But", "Goal"),
    ("Objectif", "Objective"),
    ("Projet", "Project"),
    ("Plan", "Plan"),
    ("Idée", "Idea"),
    ("Pensée", "Thought"),
    ("Opinion", "Opinion"),
    ("Avis", "Opinion"),
    ("Point de vue", "Point of view"),
    ("Vérité", "Truth"),
    ("Réalité", "Reality"),
    ("Apparence", "Appearance"),
    ("Illusion", "Illusion"),
    ("Rêve", "Dream"),
    ("Cauchemar", "Nightmare"),
    ("Espoir", "Hope"),
    ("Désespoir", "Despair"),
    ("Confiance", "Trust"),
    ("Méfiance", "Distrust"),
    ("Doute", "Doubt"),
    ("Certitude", "Certainty"),
    ("Preuve", "Proof"),
    ("Témoin", "Witness"),
    ("Témoignage", "Testimony"),
    ("Accident", "Accident"),
    ("Incident", "Incident"),
    ("Événement", "Event"),
    ("Fête", "Party / Holiday"),
    ("Célébration", "Celebration"),
    ("Cérémonie", "Ceremony"),
    ("Mariage", "Wedding"),
    ("Divorce", "Divorce"),
    ("Enterrement", "Funeral"),
    ("Baptême", "Baptism"),
    ("Anniversaire", "Birthday"),
    ("Noël", "Christmas"),
    ("Pâques", "Easter"),
    ("Nouvel An", "New Year"),
    ("Vacances", "Vacation"),
    ("Week-end", "Weekend"),
    ("Congé", "Leave"),
    ("Retraite", "Retirement"),
    ("Travail", "Work"),
    ("Emploi", "Job"),
    ("Poste", "Position"),
    ("Salaire", "Salary"),
    ("Prime", "Bonus"),
    ("Impôt", "Tax"),
    ("Facture", "Bill"),
    ("Reçu", "Receipt"),
    ("Monnaie", "Currency / Change"),
    ("Argent", "Money / Silver"),
    ("Prix", "Price"),
    ("Coût", "Cost"),
    ("Dépense", "Expense"),
    ("Revenu", "Income"),
    ("Budget", "Budget"),
    ("Économie", "Savings / Economy"),
    ("Dette", "Debt"),
    ("Crédit", "Credit"),
    ("Prêt", "Loan"),
    ("Intérêt", "Interest"),
    ("Compte", "Account"),
    ("Banque", "Bank"),
    ("Carte bancaire", "Bank card"),
    ("Chèque", "Check"),
    ("Espèces", "Cash"),
    ("Pièce", "Coin"),
    ("Billet", "Banknote"),
]

# Build database with auto examples
VOCAB_DATABASE = [
    {"word": w, "meaning": m, "example": f"Le mot « {w} » est utilisé dans la langue française."}
    for w, m in WORDS_RAW
]

# Deduplicate by word
_seen = set()
_unique = []
for item in VOCAB_DATABASE:
    key = item["word"].lower()
    if key not in _seen:
        _seen.add(key)
        _unique.append(item)
VOCAB_DATABASE = _unique

# Junk words to skip (from old API)
JUNK_WORDS = {
    "comédies", "cousable", "des avances en vue d'une négociation",
    "endomorphisme", "euphémisme", "gaillet", "géomagnétismes",
    "inflationnisme", "mission de surveillance", "migré",
    "propénols", "résultats délivrés", "vernis", "d'occasion",
}

def is_junk(word):
    return word.lower() in JUNK_WORDS

# ==========================================
# 5. MAIN PICKER
# ==========================================
def get_unique_word():
    remaining = [
        w for w in VOCAB_DATABASE
        if w["word"].lower() not in SENT_WORDS
        and not is_junk(w["word"])
    ]

    if remaining:
        item = random.choice(remaining)
        SENT_WORDS.add(item["word"].lower())
        save_sent_words(SENT_WORDS)
        return item["word"], item["meaning"], item["example"]

    # Sab khatam — recycle
    print("[WARN] All words sent! Recycling from start.")
    item = random.choice(VOCAB_DATABASE)
    return item["word"], item["meaning"], item["example"]

# ==========================================
# 6. TELEGRAM DELIVERY
# ==========================================
async def send_word():
    bot = Bot(token=TOKEN)
    word, meaning, example = get_unique_word()

    message = (
        f"🇫🇷 <b>French Word of the Hour</b>\n\n"
        f"🗣 <b>Word:</b> {html.escape(word)}\n"
        f"💡 <b>Meaning:</b> {html.escape(meaning)}\n"
        f"📝 <b>Example:</b> <i>{html.escape(example)}</i>"
    )

    await bot.send_message(chat_id=CHAT_ID, text=message, parse_mode="HTML")
    print(f"[SENT] {word}")

def job():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(send_word())
    except Exception as e:
        print(f"[JOB ERROR] {e}")
    finally:
        loop.close()

# ==========================================
# 7. SCHEDULER
# ==========================================
def scheduler_loop():
    print("⏰ First word in 5 minutes...")
    time.sleep(300)
    job()
    print("✅ First sent. Next every 1 hour.")
    while True:
        time.sleep(3600)
        job()

threading.Thread(target=scheduler_loop, daemon=True).start()

# ==========================================
# 8. KEEP ALIVE
# ==========================================
def keep_alive():
    while True:
        time.sleep(300)
        if RENDER_URL:
            try:
                requests.get(RENDER_URL, timeout=10)
            except Exception:
                pass

threading.Thread(target=keep_alive, daemon=True).start()

# ==========================================
# 9. START
# ==========================================
if __name__ == "__main__":
    print(f"🤖 Bot initialized. {len(SENT_WORDS)} words already sent.")
    print(f"📚 Total words available: {len(VOCAB_DATABASE)}")
    print("🧹 Junk filter: ACTIVE")
    while True:
        time.sleep(60)
